checkmarble/marble-backend

.env.local, repositories/ingestion_repository.go
=> allow to overwrite ingested data with the same timestamp & object_id

mocks/postgres.go, mocks/user_repository.go, models/firebase_identity.go, models/user.go, repositories/dbmodels/db_user.go, repositories/firebase/client.go, repositories/firebase/client_test.go, repositories/migrations/20240201142144_remove_firebase_uid.sql, repositories/postgres/users.go, repositories/user_repository_postgresql.go, usecases/marble_token_usecase.go, usecases/seed_usecase.go, usecases/token/generator.go, usecases/token/generator_test.go
Remove `firebase_uid` from our code.
NB: this work because of the partial unique index on user `email`
=> refactor(auth): remove firebase uid from user model

usecases/api_key_usecase.go
Small PR to enforce api key role in creation usecase
=> fix(apikeys): add role validation

usecases/scheduledexecution/run_scheduled_execution.go
I'm puzzled on why there is an error here in staging but not in prod - but a better log may help understand.
`panic: time: missing Location in call to Time.In` in staging hourly job
```
// LoadLocation returns the Location with the given name.
//
// If the name is "" or "UTC", LoadLocation returns UTC.
// If the name is "Local", LoadLocation returns Local.
//
// Otherwise, the name is taken to be a location name corresponding to a file
// in the IANA Time Zone database, such as "America/New_York".
//
// LoadLocation looks for the IANA Time Zone database in the following
// locations in order:
//
//   - the directory or uncompressed zip file named by the ZONEINFO environment variable
//   - on a Unix system, the system standard installation location
//   - $GOROOT/lib/time/zoneinfo.zip
// …
```
=> better error log if nil timezone passed in executionIsDueNow

.vscode/launch.json, go.mod, go.sum, jobs/scheduler.go, main.go, repositories/migrations.go
Scheduler to run the full app in docker compose
=> add cron scheduler to be run in docker compose

.github/workflows/backend_test_workflow.yaml
node-16 actions are deprecated
=> bump action

usecases/organization_usecase.go
To do perhaps: handle the backend's 400 error more gracefully on the front (currently: stays stuck on an error page)
=> fix: no 500 error on admin user login

router.go
That is the correct setting, right ?
=> fix allowed origin for cors outside of dev mode

models/ast/ast_node_evaluation.go, usecases/ast_eval/evaluate_ast_expression.go, usecases/decision_usecase.go, usecases/evaluate_scenario/evaluate_scenario.go, usecases/scheduledexecution/run_scheduled_execution.go, usecases/usecases.go, usecases/usecases_with_creds.go
First PR to expose `NodeEvaluation` to scenario evaluation.
I prefer to show you this refactor before moving forward.
=> refactor(ast-evaluation): return RootNodeEvaluation instead of bool

api/api.go
To reduce the bottleneck on file upload
=> increase read timeout on server

.vscode/settings.json, jobs/execute_all_scheduled_scenarios.go, jobs/schedule_due_scenarios.go
See doc https://docs.sentry.io/platforms/go/crons/
We have 1 included in our pricing plan but we can buy additional ones if it works well
(if it works well I may also implement an abstraction above "execute a cron job" because otherwise it's a lot of boilerplate"
=> setup sentry cron monitor for scheduled execution

api/routes.go
=> feat: add 408 timeout on batch ingestion

dto/pagination.go, specs/public-api.yaml
Already handle using `offet_id` in thre frontend app
=> fix(dto): change offsetId to offset_id

repositories/data_model_repository.go, repositories/ingestion_repository.go
See discussion here https://checkmarble.slack.com/archives/C063SMVJ4BY/p1713432113875619
=> tentative fix to avoid lock on data model enum values update

dto/data_model_dto.go
Title is self explanatory
PS: this work is taken into account in [this frontend PR](https://github.com/checkmarble/marble-frontend/pull/433)
=> refactor(dto): remove omitempty from ID field in Field and Table structs

api/routes.go, dto/data_model_dto.go
Small update did during the create pivot implementation described [here](https://github.com/checkmarble/marble-frontend/pull/435)
=> Thomas/mar 534 create UI for a data model pivot

dto/user_dto.go, repositories/user_repository_postgresql.go
Small changes to allow create users by API
=> feat(partner): allow to create users with partner_id

specs/public_api.yaml, specs/transfercheck_api.yaml
New source of truth for the API doc (instead of https://www.notion.so/checkmarble/Transfercheck-Public-open-API-20164379267448a9b73304e270c6c0cd)
=> add transfercheck openapi

repositories/transfercheck_enrichment.go
=> fix dumb error on enrichmetn data expiration

dto/transfer_check.go, models/transfer_check.go, specs/transfercheck_api.yaml
Remains to do: define the exact list of values we want to use: https://checkmarble.slack.com/archives/C06Q995LQCB/p1718790927395749?thread_ts=1718790335.969849&cid=C06Q995LQCB
=> done
---
I added the field in my local transfercheck org and the staging one (our staging) and the sandbox in our prod env one. Remember to add it in your local org if you have one.
I also updated the [org setup guide](https://www.notion.so/checkmarble/Org-setup-guide-984e368f113e434f97f42aaa6424e60c) with it
=> required sender account type for transfercheck

api/handle_partner.go, cmd/server.go, dto/partner_dto.go, models/partner.go, repositories/dbmodels/db_partner.go, repositories/migrations/20240627115100_partner_bic.sql, repositories/transfercheck_partners.go, usecases/partner_usecase.go
The first commit is a bugfix: a new key was generated at every server startup. This probably has caused some unwanted 401s in the front.
---- 
The BIC is supposed to be the 8 char bic, but I'm not strictly enforcing this for now
=> add bic field on partner with related CRUD operations

api/handle_transfer_alerts.go, api/handle_transfer_check.go, api/routes.go, dto/transfer_alerts.go, models/transfer_alerts.go, models/transfer_check.go, repositories/dbmodels/db_data_model.go, repositories/dbmodels/db_transfer_alerts.go, repositories/migrations/20240628170500_introduce_transfer_alerts.sql, repositories/transfer_alerts.go, repositories/transfercheck_partners.go, usecases/security/enforce_security_transfer_check.go, usecases/transfer_alerts.go, usecases/transfer_check_usecase.go, usecases/transfers_data_read/transfers_data_read.go, usecases/usecases_with_creds.go
Following [the notion note](https://www.notion.so/checkmarble/Transfer-alerts-4b9de1a0088c4dd78e95229354b59010)
--- 
Postman collection added
--- 
Some dependency on https://github.com/checkmarble/marble-backend/pull/610 for finding the beneficiary partner by BIC
=> introduce models & api endpoints

usecases/indexes/index_family.go
At the end of the day, the error was super trivial yet super annoying to debug.
=> fix stupid bug with duplicate indexes created

api-clients/convoy/api.yaml, api-clients/convoy/cfg.yaml, api-clients/convoy/client.gen.go, api/handle_webhooks.go, api/routes.go, dto/webhooks.go, models/webhook.go, repositories/convoy_repository.go, repositories/convoy_repository_test.go, usecases/security/enforce_security_webhook.go, usecases/webhooks_usecase.go, utils/organization_security.go
NB: Full required endpoints are not yet done but I want you to share your opinion
=> feat(webhooks): list all webhooks

api/handle_webhooks.go, api/routes.go, usecases/webhooks_usecase.go
Add get by id endpoint
NB: I did not created any new permission, so anyone that can list webhooks can also retrieve webhook detail (with secret)
=> feat(webhooks): add get webhook by id endpoint

cmd/batch_ingestion.go, cmd/schedule_scenarios.go, cmd/scheduled_executor.go, repositories/convoy_repository.go, repositories/repositories.go
I tested the feature locally... but only with the job scheduled as entrypoint, which has its own parsing of env variables & repositories setup. And I tested the feature on staging... but no the batch exec 🤕 
I'll make a fix release with this, which should be the last one this week probably
=> hotfix: error sending webhooks on scheduled batch execution

specs/public_api.yaml, specs/readme.md, specs/transfercheck_api.yaml
In this PR :
- update OAS specs with custom properties for Readme (in order to change proposed code snippets)
- update our internal README to prevent issues like the one I did in the future
=> chore(specs): update oas files and readme

dto/license_dto.go, usecases/evaluate_scenario/evaluate_scenario.go
- DTO key for license should be plural
- other PR suggestions, including a bug fix
=> PR comment fixes for snoozes

jobs/execute_all_scheduled_scenarios.go, mocks/scheduled_execution_usecase_repository_mock.go, models/scheduled_scenario_executions.go, repositories/scheduled_executions.go, usecases/scheduled_execution_usecase.go, usecases/scheduledexecution/run_scheduled_execution.go
Largely inspired from https://github.com/checkmarble/marble-backend/pull/659.
Especially, properly set status to failed if the job times out (3 hours)
---
See also related front end update in https://github.com/checkmarble/marble-frontend/pull/528
=> proper timeout handling on scheduled execution

dto/custom_list_dto.go, dto/rule_dto.go, dto/scenario_iterations.go, dto/scenario_publications.go, dto/scenarios.go, integration_test/api_end_to_end_test.go
With https://github.com/checkmarble/marble-frontend/pull/536
=> remove deprecated dto fields

api/handle_decision.go, dto/case_dto.go, dto/decision_dto.go, integration_test/generate_usecases.go, integration_test/scenario_flow_test.go, models/decision.go, repositories/analytics_views/decisions.sql, repositories/dbmodels/db_decision.go, repositories/decisions_repository.go, repositories/migrations/20240909165500_decisions_review_status.sql, repositories/migrations/20240909173500_decisions_drop_error_code.sql, usecases/scheduledexecution/export_schedule_execution.go
- 1st commit contains the actual changes
- 2nd commit is only types renaming
- 3rd commits makes nullable a field I want to remove
Can be reviewed, pending discussion with Arnaud on the actual values we use
=> new review status field on decisions

api/handle_cases.go, api/routes.go, dto/case_dto.go, models/case.go, models/case_event.go, models/decision.go, repositories/decisions_repository.go, usecases/case_usecase.go
Goes with https://github.com/checkmarble/marble-frontend/pull/537
=> expose case action to review a decision

usecases/decision_usecase.go
Small miss in the filter by review status implem
=> fix: add ReviewStatuses to ListDecisions

repositories/blob_repository.go
Forgot to remove this line, which I was using during initial attemps
=> fix error on key parsing

repositories/migrations/20240923141200_remove_batch_trigger_sql.sql
Finishing a migration from the previous week
=> remove unused batch_trigger_sql field

repositories/ingested_data_read_repository.go, usecases/scheduled_execution/run_scheduled_execution.go
See https://checkmarble.slack.com/archives/C04JB5ZADBN/p1728394061965309:
I'll run with this + change the value of GOMEMLIMIT, GOGC on the relevant job which seems to work well enough.
----
Goes together with this one https://github.com/checkmarble/terraform/pull/34
=> tentative improvements on memory usage

.github/workflows/backend_deploy_workflow.yaml
Re-sync with https://github.com/checkmarble/terraform/pull/36
=> fix CICD: deploy a service not a job

usecases/evaluate_scenario/evaluate_scenario.go
Set more information on traces for better debugging possibilities
=> more details on scenario evaluation trace

api/handle_analytics.go, api/handle_apikey.go, api/handle_cases.go, api/handle_custom_list.go, api/handle_datamodel.go, api/handle_datamodel_pivot.go, api/handle_decision.go, api/handle_editor.go, api/handle_inboxes.go, api/handle_ingestion.go, api/handle_license.go, api/handle_liveness_probe.go, api/handle_organization.go, api/handle_partner.go, api/handle_post_firebase_id_token.go, api/handle_rules.go, api/handle_scenario_iterations.go, api/handle_scenario_publications.go, api/handle_scenarios.go, api/handle_scheduled_execution.go, api/handle_snoozes.go, api/handle_tags.go, api/handle_transfer_alerts.go, api/handle_transfer_check.go, api/handle_users.go, api/handle_webhooks.go, api/middleware.go
=> move calls to c.Request.Context() to context we already extracted

api/server.go
Reverts checkmarble/marble-backend#749
One of the 2 PRs I merged this morning must be causing the glitch, my bet is on this one
=> Revert "avoid mac firewall getting in the way of end to end tests"

dto/license_dto.go, models/license.go, repositories/dbmodels/db_license.go, repositories/license_repository.go, repositories/migrations/20241210134900_licences_test_run.sql
Adapt the license object & DTO to include the test run feature
=> license server: test run feature

api/handle_cases.go, models/case_files.go, models/webhook.go, usecases/case_usecase.go
Lay down the refacto necessary to allow multi-file upload.
Goes with [this frontend PR](https://github.com/checkmarble/marble-frontend/pull/624)
⚠️ this change is breaking on the API, deliver frontend + backend PR together ⚠️
=> multi-file upload

.env.example, api/configuration.go, api/routes.go, api/server.go, cmd/server.go, integration_test/init_test.go
Small refactor to allow configuring timeout with env vars.
=> chore: add timeout configuration to env variables

.github/workflows/backend_deploy_workflow.yaml, .github/workflows/deploy_production.yaml, .github/workflows/deploy_staging.yaml
Related to PR https://github.com/checkmarble/terraform/pull/49 which contains the main notes on the implementation (notion and code comments)
=> test: workload identity

api/handle_datamodel.go, api/routes.go, dto/data_model_dto.go
Following accidental deletion here https://github.com/checkmarble/marble-backend/pull/663/files#diff-98ba00aec3a81a2ed9b83cab1c3de9ae182c63060b8d8a4a06bb443f90648e52L153
=> re-add the endpoint to update table description

models/ast/ast_function.go, models/ast/ast_node_weight_test.go
I misunderstood the payload node. Should its cost be set to 0?
=> Payload node cost should be 0

api/handle_datamodel.go, api/handle_ingestion.go, api/routes.go, dto/data_model_dto.go, models/data_model.go, repositories/ingested_data_read_repository.go, usecases/ingested_data_reader_usecase.go, usecases/scheduled_execution/async_decision_job.go, usecases/transfers_data_read/transfers_data_read.go, usecases/usecases_with_creds.go
Add endpoint `/data/:tableName/:objectID` which returns ingested object data
=> feat: add endpoint to get ingested object data

go.mod, go.sum, models/ast/ast_node.go, models/ast/ast_node_evaluation.go, models/ast/node_evaluation_dto.go, usecases/ast_eval/evaluate_ast.go, usecases/ast_eval/evaluate_ast_expression.go, usecases/ast_eval/evaluate_ast_test.go, usecases/ast_eval/weighted_nodes.go, usecases/evaluate_scenario/evaluate_scenario.go, usecases/scenarios/scenario_validation.go
Reverts checkmarble/marble-backend#811
=> Revert "Cache node evaluation to reuse results within a run"

api/handle_sanction_checks.go, api/handle_scenario_iterations.go, api/routes.go, dto/sanction_check_config_dto.go, dto/scenario_iterations.go, mocks/sanction_check_config_repository.go, models/scenario_iterations.go, repositories/dbmodels/db_sanction_check_config.go, repositories/migrations/20250206082400_sanction_checks_rule_metadata.sql, repositories/sanction_check_config_repository.go, usecases/evaluate_scenario/evaluate_sanction_check.go, usecases/evaluate_scenario/evaluate_sanction_check_test.go, usecases/sanction_check_config_usecase.go, usecases/sanction_check_usecase.go, usecases/scenario_iterations_usecase.go, usecases/scenarios/scenario_validation.go, usecases/usecases_with_creds.go
Adds:
* Metadata on sanction check config (name, description, rule_group)
* Refinement dry-run
* Fixes to draft creation
* Separate sanction check config writing into discrete endpoints
* Sanction check validation within scenario iteration validation
=> Various API improvements

api/handle_sanction_checks.go, api/routes.go, dto/sanction_check_dto.go, models/sanction_check.go, usecases/sanction_check_usecase.go
For V1, comments can should only be added when reviewing a match, and there can only be one per match.
=> Allow adding a comment when reviewing a match.

go.mod, go.sum, models/ast/ast_node.go, models/ast/ast_node_evaluation.go, models/ast/node_evaluation_dto.go, usecases/ast_eval/evaluate_ast.go, usecases/ast_eval/evaluate_ast_expression.go, usecases/ast_eval/evaluate_ast_test.go, usecases/ast_eval/weighted_nodes.go, usecases/evaluate_scenario/evaluate_scenario.go, usecases/scenarios/scenario_validation.go
Reverts checkmarble/marble-backend#830
=> Fixing cached evaluation

api/handle_sanction_checks.go, api/routes.go, dto/sanction_check_dataset_dto.go, go.mod, go.sum, models/opensanctions.go, repositories/httpmodels/http_opensanctions_dataset.go, repositories/httpmodels/http_opensanctions_dataset_freshness.go, repositories/opensanctions_repository.go, repositories/opensanctions_repository_test.go, usecases/sanction_check_usecase.go
Basic version until we map out what to do with it.
=> OpenSanctions dataset catalog

models/ast/evaluation_error_dto.go, models/ast/evaluation_errors.go, usecases/ast_eval/evaluate/evaluate_aggregator.go
Frontend PR : https://github.com/checkmarble/marble-frontend/pull/691
=> feat: add errors on aggregate filters

dto/sanction_check_dto.go, models/sanction_check.go, repositories/dbmodels/db_sanction_check.go, repositories/migrations/20250218103800_add_sanction_check_error_codes.sql, repositories/sanction_check_config_repository.go, repositories/sanction_check_repository.go, usecases/ast_eval/evaluate/eval_string_concat.go, usecases/evaluate_scenario/evaluate_sanction_check.go, usecases/sanction_check_usecase_test.go
Also fixes a panic introduced with the refactoring of forced outcome.
=> Add sanction check run error codes

dto/openapi.go
This fixes the OpenAPI generation in two ways:
* `$ref` becomes `omitempty`
* When we build the endpoint matrix `/ingest/*` / `/ingest/*/multiple` / `POST` / `PATCH`, we inadvertently modified pointers to the previously-built object, making the final output invalid.
=> Fix OpenAPI validation

.env.example, api/configuration.go, api/handle_decision.go, api/router.go, api/routes.go, api/server.go, cmd/server.go, dto/case_dto.go, dto/decision_dto.go, integration_test/init_test.go, usecases/scheduled_execution/export_schedule_execution.go
Prerequisite for the PR https://github.com/checkmarble/marble/pull/80, see link
=> some breaking changes on env var urls expected on the backend

usecases/scheduled_execution/index_creation_job.go
We introduced a bug where indices with several columns would routinely overflow Postgres max length for index names, which would trigger a logic bug in the detection of indices ongoing creation. This fixes that.
=> Fixed index creation when index names were too long.

.github/workflows/backend_test_workflow.yaml, Dockerfile, go.mod, models/aggregate_query.go, usecases/indexes/aggregate_query.go, usecases/indexes/aggregate_query_test.go, usecases/indexes/aggregate_query_to_idx_test.go, usecases/indexes/index_family.go, usecases/indexes/index_family_test.go
I guess it was time ? 👀 
warning @checkmarble/devs  you'll need to upgrade your local go version
=> bump go version 1.24

usecases/ingestion_usecase.go
We had an issue when, if the CSV headers failed to parse after upload, a 500 error would be sent, which did not convey the error message to the frontend.
This PR:
* Returns a 400 if headers fail to parse
* Returns a subjectively better error message in that case
New error messages look like:
* `error reading CSV first header (column 11): bare " in non-quoted-field: bad parameter`
* `error reading CSV header after "firstname" (column 30): bare " in non-quoted-field: bad parameter`
=> Better ingestion errors

usecases/ingestion_usecase.go
This follows #909.
Ingestion through CSV has some edge cases where the provided format is not exactly what we expect. This PR adds handling of the following:
* Semicolons are used as separator
* Header names have leading or trailing whitespaces
=> Add ingestion special case error messages.

api/handle_signup_status.go, api/routes.go, mocks/user_repository.go, repositories/organization_repository.go, repositories/user_repository_postgresql.go, usecases/signup_usecase.go
=> feat(signup): add an enpoint to ensure db is ready for first signup

README.md
This PR adds a paragraph about the components that compose the backend service, it also points out that the worker is necessary for some core features of the API.
=> Detail the structure of the backend in the README.

usecases/ast_eval/evaluate/eval_is_multiple_of.go
Title & comment in code says it all
=> hande nil values in "is multiple of" operator

models/case_event.go, usecases/case_usecase.go, usecases/suspicious_activity_report_usecase.go
Added new events for:
* Case assigned
* Suspicious Activity Report created
* Suspicious Activity Report deleted
* Suspicious Activity Report status update
* Suspicious Activity Report file uploaded
=> Added various case events.

models/ast/ast_filter.go, models/ast/ast_function.go, repositories/ingested_data_read_repository.go, repositories/ingested_data_read_repository_test.go, usecases/ast_eval/evaluate/evaluate_filter.go, usecases/ast_eval/evaluate/evaluate_fuzzy_match_options.go, usecases/ast_eval/evaluate/evaluate_fuzzy_match_options_test.go, usecases/ast_eval/evaluate_environment.go, usecases/indexes/aggregate_query.go
- **feat(AST-builder): add simple Fuzzy match filter**
=> feat: fuzzy match aggregate filter

usecases/case_usecase.go, usecases/suspicious_activity_report_usecase.go
Various update events on cases should self-assign the case to the actor:
* Updates
* Snooze / unsnooze
* Actions on suspicious activity reports
* Comments
* Tags update
=> Self-assign case on various events.

repositories/decisions_repository.go
Fixes this error https://checkmarble.slack.com/archives/C08PWMSBVQR/p1746433771774399
=> fix: backend 500 error if null value pivot value present in case

dto/case_dto.go, models/case.go
Preparation for https://linear.app/marble-eu/issue/MAR-974/use-the-revamped-decision-outcome-and-case-status-icons-in-case
=> return full status for cases, including snoozed & waiting for action

dto/case_dto.go, models/case.go
Reverts checkmarble/marble-backend#1002
Should not have merged yet
=> Revert "return full status for cases, including snoozed & waiting for action"

repositories/case_and_decisions.go, usecases/decision_workflows/decision_workflows.go
Just minor refactoring of code written while I was looking up usage cases for some indexes on decisions.
=> small refactoring of decision workflow

repositories/case_repository.go
Order included "boost is null", but not the pagination condition.
=> fix: pagination was broken with boosted cases

repositories/decisions_repository.go, repositories/offloading_repository.go, usecases/scheduled_execution/offloading_job.go
https://linear.app/marble-eu/issue/MAR-1033/issues-with-offloading
=> Fixed issues with offloading job.

dto/agent_dto/case.go, dto/agent_dto/client_data.go, dto/agent_dto/decisions.go, infra/sentry.go, models/client_data_object.go, models/user.go, usecases/ai_agent_usecase.go
- improves zip export by writing all to a writer without intermediate bytes
- rework dtos for agent data export
- add exported data on related cases, ingested client data as csv
=> rework dtos and add related cases data in export

repositories/migrations/20250605000000_allow_multiple_screenings.sql
=> But really delete those orphan sanction checks.

api/handle_config.go, dto/config_dto.go, infra/verify_license.go, models/license.go, usecases/license_usecase.go
See https://checkmarble.slack.com/archives/C04JB5ZADBN/p1752655749715449?thread_ts=1752652804.405579&cid=C04JB5ZADBN
& related PR https://github.com/checkmarble/marble-frontend/pull/980
=> backend returns information if marble is managed saas

api/handle_workflows.go, api/routes.go, repositories/workflows_repositories.go, usecases/workflows_usecase.go
Add a new endpoint to fetch a single rule with details of conditions and actions
=> feat(workflows): Get rule details

repositories/case_review_repository.go, repositories/migrations/20250808122214_add_index_created_at_ai_case_review.sql, usecases/metrics_collection/ai_case_review_collector.go, usecases/metrics_collection/collector.go, usecases/metrics_collection/collector_test.go, usecases/metrics_collection/constant.go
This pull request introduces a new metric collector for counting AI case reviews by organization, integrates it into the metrics collection system, and optimizes related database queries. The main themes are feature addition, repository interface expansion, database performance, and test coverage.
**Feature Addition: AI Case Review Collector**
* Added `AiCaseReviewCollector` in `ai_case_review_collector.go` to count AI case reviews per organization over daily periods, implementing the `Collector` interface.
* Defined the metric name constant `AiCaseReviewCountMetricName` for AI case review counts.
**Repository Interface Expansion**
* Added `AiCaseReviewCollectorRepository` to the `CollectorRepository` interface and implemented the method `CountAiCaseReviewsByOrg` in …
=> feat(metrics_collection): add AI case review metrics collector and database migration for indexing

usecases/ai_agent/ai_agent_usecase.go, usecases/ai_agent/ai_enrichment_usecase.go
This pull request refactors how prompt templates and organization-specific instructions are handled in the AI agent use cases, improving maintainability and flexibility. It centralizes prompt path constants, replaces file-based organization instructions with database-driven settings, and introduces clearer separation between prompt preparation and model selection. Additionally, it updates the enrichment logic to use organization settings and supports provider-specific options.
**Prompt and Model Handling Improvements:**
* Centralized all prompt file paths as constants at the top of `ai_agent_usecase.go` and `ai_enrichment_usecase.go`, simplifying future changes and reducing duplication. [[1]](diffhunk://#diff-79313301e7a350d0a80f5cd35e124a50c9851ea0d79cf2984fb6122bedfb370aR37-R49) …
=> feat(ai_agent): use ai setting in ai usecase

repositories/migrations/20251001151300_add_workflow_audit_trail.sql
New audit events will now be added on every action editing a scenario workflow.
=> Add audit trail events on workflow edition.

api/handle_datamodel_exported_fields.go, api/routes.go, dto/analytics_settings.go, repositories/analytics_settings.go, repositories/dbmodels/db_analytics_settings.go, usecases/analytics_settings.go, usecases/usecases_with_creds.go
Adds the two endpoints used to configure how analytics data is exported (mainly which fields should be added to the tables).
=> Implement analytics settings endpoints.
