- usecases/ingestion_usecase.go
By doing ingestion locally, I found that :
- there is an error on the line number computation
- we can leverage some usefull CSV parser error (to help the user understand why there is a problem)
As we display raw error messages in the frontend, I assume we can live with that for now
> feat(ingestion): improve error messages

- integration_test/init_test.go
- main.go
- repositories/migrations.go
- repositories/postgres/postgres.go
- utils/database.go
Related change in env vars for our cloud run: https://github.com/checkmarble/terraform/pull/11
Short explanation:
- as we're connecting through a socket from cloud Run to Cloud Sql because the former is serverless and the latter has a firewall (see [doc](https://cloud.google.com/sql/docs/postgres/connect-run)), we were ignoring the database port env variable if not running in development mode.
- that was fine for us but is not the general case and is presumably blocking for others running marble as open source
> fix: ignore port for db only if connecting through unix socket

- models/aggregate_query.go
- repositories/ingested_data_indexes_repository.go
- usecases/indexes/aggregate_query.go
- usecases/indexes/aggregate_query_test.go
- usecases/indexes/aggregate_query_to_idx_test.go
- utils/sentry.go
+ Add sentry log when an error happens while creating indexes (needed because the error doesn't bubble up back to the api request handler)
> fix: need not create indexes if no field is indexable

- infra/postgres_connections_pool.go
- router.go
To be considered in the context of https://github.com/checkmarble/terraform/pull/14.
Max_instances*max_connections_per_pool should remain broadly lesser than the db instance's max connections (this is an approximation, because we also have to account for cron jobs)
For context:
- the staging DB with 1 vcpu and 4Gb RAM has max 100 connections
- the prod DB with 4 vcpu and 1Gb RAM has max 500 connections
- max connections are broadly proportional to RAM IIUC
> reduce db pool max connections

- README.md
- go.mod
- usecases/evaluate_scenario/evaluate_scenario.go
Seems blocked as per https://github.com/github/roadmap/issues/918
> bump go version: 1.22

- api/handle_cases.go
- api/handle_scenario_iterations.go
- api/handle_scenarios.go
- dto/case_event_dto.go
- dto/scenario_iterations.go
- dto/scenarios.go
- go.mod
- go.sum
- integration_test/scenario_flow_test.go
- models/case_event.go
- models/decisions.go
- models/scenario_iterations.go
- models/scenarios.go
- repositories/case_event_repository.go
- repositories/dbmodels/db_case_event.go
- repositories/dbmodels/db_scenario.go
- repositories/migrations/20240301225900_case_event_userid_nullable.sql
- repositories/migrations/20240304105230_scenario_decision_to_case_settings.sql
- repositories/scenario_iterations_write.go
- repositories/scenarios_write.go
- usecases/case_usecase.go
- usecases/decision_usecase.go
- usecases/scenario_iterations_usecase.go
- usecases/scenario_usecase.go
- usecases/usecases_with_creds.go
- New field `decision_to_case_inbox` and `decision_to_case_outcomes` on the scenario (models, dto, db).
- If both are not nil and the decision's outcome is in decision_to_case_outcomes, then create a automatically
- Permission check on inbox reading is bypassed: in API context, the inbox id on the scenario is the source of truth. 
- Pending question (but the code is reviewable as it is): what level of permission to update those settings on the scenario -> Edit: publisher permission required to udpate the settings
Commit 5: [48c8313](https://github.com/checkmarble/marble-backend/pull/495/commits/48c831353629bf9bccb8c22de1a345f7013a4762): just cleaning up dtos & models, many line changes but no logic change
Related front PR: https://github.com/checkmarble/marble-frontend/pull/392
The idea …
> feat: automatically create case from decision

- dto/apikey_dto.go
- integration_test/scenario_flow_test.go
- mocks/api_key_repository.go
- models/api_key.go
- repositories/api_key_repository.go
- repositories/dbmodels/db_api_key.go
- repositories/migrations/20240304155400_hash_apikeys.sql
- repositories/postgres/api_keys.go
- usecases/api_key_usecase.go
- usecases/api_key_usecase_test.go
- usecases/token/generator_test.go
- usecases/token/validator_test.go
- usecases/usecases_with_creds.go
- introduce new field on api keys "hash", store it on creation and backfill it with the old keys hashed value
- for now continue using the non hashed key for matching
- in follow-up PR, use the hashed key for matching
- then finally, drop the key column (or reuse it to store just the prefix of the key, for display like `123##############`)
- while I'm at it, add a created_at field to return them in order
Security:
- we use 32 bytes of entropy to generate the keys, so no need to salt them
- SHA256 to hash the keys (industry standard)
> introduce hash field for api keys

- repositories/ingested_data_read_repository.go
- repositories/ingested_data_read_repository_test.go
Db field read:
- would fail with unexpected error if the child field was not present in the payload (e.g. account_id absent in transaction payload)
- would not work if the link was pointing to a parent table field other than object_id (would generate a wrong query)
> fix error on db field read

- .env.example
- Dockerfile
- api/api.go
- api/middleware/logging.go
- api/routes.go
- infra/parse_signing_key.go
- main.go
- repositories/firebase/client.go
- repositories/firebase/client_test.go
- router.go
- usecases/data_model_usecase_test.go
- usecases/indexes/aggregate_query_test.go
- usecases/indexes/index_editor_test.go
- usecases/scenario_publication_usecase_test.go
- usecases/scenarios/scenario_validation_test.go
- utils/context_logging.go
- new env variable "enable_gc_tracing" (requires application default credentials to run)
- use alpine instead of distroless image to have access to wget to use in docker-compose health checks
- better documentation of what env variables do
- drop "VerifySessionCookie" logic in auth middleware, that was no longer supposed to be used but messed up all our error logging related to token validation
> small changes for deployment with docker compose

- Dockerfile
See
https://lalatron.hashnode.dev/a-story-about-go-docker-and-time-zones
https://stackoverflow.com/questions/59094236/error-unknown-time-zone-america-los-angeles-in-time-loadlocation
The error was introduced by using alpine as the base image, which does not include the tz definitions by default (turns out the tz info is handled by the environment not hard coded in the std lib)
> tentative fix for timezone load

- usecases/ingestion_usecase.go
- usecases/usecases_with_creds.go
To keep it short: when running in batch as a cron script, rather than from a server query, we don't have a specific org's id in the "usecase with credentials".
It's really a limitation of how we currently inject those dependencies & context into usecases, and something I want to review at some point - but for today this quick fix will have to do (here, the GetDataModel in the usecase was failing because it's reading the indexes which requires the context org id to get the relevant schema, while the repository method of the same name "only" reads the tables as described in data_model_tables/fields/links, which does not require access to the client schema)
> fix: ingestion in batch was broken because of context org id in batch job mode

- api/handle_decision.go
- dto/case_dto.go
- dto/decision_dto.go
- integration_test/scenario_flow_test.go
- models/case.go
- models/decision.go
- repositories/analytics_repository.go
- repositories/dbmodels/db_decision.go
- repositories/decisions_repository.go
- repositories/scenario_iterations_write.go
- usecases/decision_usecase.go
- usecases/scenario_iterations_usecase.go
- usecases/scheduledexecution/export_schedule_execution.go
- usecases/scheduledexecution/run_scheduled_execution.go
When getting a decision by id, populate rule asts
EDIT: I needed to add `score_modifier` since on the DTO we expose the "result" score as `score_modifier` (I need the real score modif of the rule for detail display)
What I really need here, is a validation of the direction I took. I'm not sure the way I build struct is the good one... Still, I choose to create `rule_detail` in order to avoid breaking change on the API (IIUC, this endpoint is on the public API inside the readme, we may need to update it)
> feat(api): add decision rule ast to decision response

- repositories/migrations/20240325143700_introduce_partners.sql
- repositories/migrations/20240327153500_ingested_tables_primary_keys.sql
- repositories/organization_schema_repository.go
Fix: stupid: the ingested tables were missing a primary key (& its related index). This was causing really slow updates at insertion time.
The attached migration is a one-of migration script that will drop all primary keys (should be none, except the one I just manually created in prod) and recreates them
> fix: make id the primary key of the ingested tables

- go.mod
- go.sum
- integration_test/scenario_flow_test.go
- models/ast/ast_function.go
- pure_utils/strings.go
- usecases/ast_eval/evaluate/adaptArgument.go
- usecases/ast_eval/evaluate/eval_fuzzy_match.go
- usecases/ast_eval/evaluate/eval_fuzzy_match_test.go
- usecases/ast_eval/evaluate/evaluate_custom_list_values.go
- usecases/ast_eval/evaluate/evaluate_database_access.go
- usecases/ast_eval/evaluate/evaluate_read_payload.go
- usecases/ast_eval/evaluate_environment.go
- utils/uuid.go
Scope:
- integrate a new operator for string to string matching
- also for string to list of strings matching (similar to what we did on "contains")
- clean up the input strings as best as possible
-----
Below copy paste from Slack conv for context 
Ok, après réflexion, mon plan pour le fuzzy matching:
- J'implémente un opérateur FuzzyMatch
- Il prend en opérande 1 et 2 deux strings
- il prend en named operand "algorithm" un choix parmi les algos pertinents de scoring (ratio, partial_ratio, etc, comme dans la lib de référence en python - portée en go)
- il retourne un score (nombre) entre 0 et 100
- De même un opérateur FuzzyMatchAnyOf, qui fait la même chose mais reçoit une string et une liste de strings
- ⚠️   comme discuté, je commence par ça mais il ne marchera pas en tant que filtre …
> add fuzzy matching operators

- .env.example
- api/api.go
- api/handle_decision.go
- dto/case_dto.go
- dto/decision_dto.go
- go.mod
- main.go
- models/global_configuration.go
- usecases/scheduledexecution/export_schedule_execution.go
For an API response body like this 
```json
{
"id": "585906d7-ea00-4181-9946-26246f561a58",
"app_link": "https://localhost:3000/decisions/585906d7-ea00-4181-9946-26246f561a58",
"created_at": "2024-03-26T13:52:17.238933+01:00",
[...]
}
```
Returns `null` if the env variable is not set, and also for decisions nested in the "cases" object return by the cases API
-----
Caveat: I use https:// by default as the scheme, which means if the url is used locally it will give an error "Ce site ne peut pas fournir de connexion sécurisée", but I still prefer that to exposing one more env variable to allow unsecured http links which will work only in dev mode anyway.
> return decision app link in API decision object

- api/handle_ingestion.go
- go.mod
- go.sum
- repositories/ingestion_repository.go
- usecases/ingestion_usecase.go
The context is that, since the introduction of a unique index on object_id on ingested tables, we can have conflicts at insertion.
Actually, also on unique fields other than the object_id, which is kind of annoying.
In here, I propose to retry (3 times) the repository ingestPayload method, if a conflict is detected.
The problem is that conflicts on object_id are sort of expected (can happen in case of concurrent calls) and should be retried (normally, it should pass on the first retry, unless there is an unreasonable number of concurrent calls on the same object). While conflict errors on other unique fields really shouldn't be retried (because we don't have logic in the code that looks it up by that key, and updates accordingly).
But in practice it's hard for me to differenciate between …
> feat: retry ingestion in case of conflict

- mocks/custom_list_repository.go
- repositories/custom_list_repository.go
- repositories/migrations/20240402153800_audit_trail_trigger.sql
- repositories/utils.go
- usecases/custom_list_usecase.go
- usecases/organization/organization_creator.go
The three options on the table were:
1. audit information directly on the table (e.g. "added_by", "deleted_by" columns, etc)
2. centralized audit table, handled in our code (run the actions in transactions, try to insert rows by calling a repo from the usecase, etc)
3. or as done here: use postgresql triggers to handle the logic.
Pros:
- it kind of just works out of the box
- very low code overhead
- could be branched off to solution 2 if needed sometime later
Cons:
- it's a bit too magic to be totally reliable (in the sense of "people are aware of it and won't accidentally break it")
- harder to have really fine control on which events we want to audit or not (well, we can possibly fine tune it more but at the cost of making the point above even worse)
All in all, I'm happy with what …
> feature: audit trail on custom list value insertion

- api/handle_transfer_check.go
- api/routes.go
- models/errors.go
- models/transfer_check.go
- pure_utils/currencies.go
- usecases/transfer_check_usecase.go
- actually hash the beneficiary iban
- but do it only if we don't already receive a hash (well, something that looks like a hash - namely 32 bytes in hexa)
- while we're at it, add some more input validation on the other fields that are expected
- caveat: some fields are format validate by gin at the binding layer, while some fields are validated in the code, and that results in different error api returns - but good enough for now
- expected formats:
- bic: 8 or 11 chars, alphanumeric
- iban: alphanumeric, 16 to 34 chars (or already a SHA256 hash in hexadecimal representation)
- currency: a valid ISO3 currency code
- ip address: a valid ip address
- status: one of "neutral", "suspected_fraud", "confirmed_fraud"
- beneficiary_name, label, sender_device: free string, max 140 chars
- …
> WIP - transfercheck input validation & hashing

- api/handle_datamodel_pivot.go
- api/routes.go
- dto/data_model_dto.go
- dto/data_model_pivot.go
- dto/decision_dto.go
- dto/openapi.go
- integration_test/scenario_flow_test.go
- mocks/data_model_repository.go
- models/concrete_index.go
- models/data_model.go
- models/data_model_pivot.go
- repositories/data_model_repository.go
- repositories/dbmodels/db_data_model.go
- repositories/dbmodels/db_data_model_pivot.go
- repositories/ingested_data_read_repository.go
- repositories/ingested_data_read_repository_test.go
- repositories/ingestion_repository.go
- repositories/migrations/20240419115400_data_model_pivot.sql
- usecases/ast_eval/evaluate/dry_run_fake_value.go
- usecases/ast_eval/evaluate/evaluate_database_access_test.go
- usecases/ast_expression_usecase.go
- usecases/ast_expression_usecase_test.go
- usecases/data_model_helpers_test.go
- usecases/data_model_usecase.go
- usecases/data_model_usecase_test.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/ingestion_usecase.go
- usecases/payload_parser/payload.go
- utils/dummy_datamodel.go
Cf note on https://www.notion.so/checkmarble/Defining-a-pivot-67cf95c5a94249fa95ba8c183e54751b (doc update following the implementation).
We're keeping open the option to select a field on the last table of the path as the pivot, for now it's only possible to select a field if the pivot is on the base table.
---- 
E.g. 
`POST /data-model/pivots`
```
{
"base_table_id": "2c8215d6-418a-47c3-a46e-7f95c67dab38",
"path_link_ids": ["c6cbc438-f3c5-4c0c-9200-cc7553bf1be6","07dfde2b-ee9b-4936-9b05-9a524ec0f306"]
}
```
=> return
```
{
"pivot": 
{
"id": "70f88448-439a-460f-ba26-0de41f159824",
"created_at": "2024-04-22T16:55:57.26021+02:00",
"base_table": "transactions",
"base_table_id": "2c8215d6-418a-47c3-a46e-7f95c67dab38",
"pivot_table": "new_table",
"pivot_table_id": …
```
> first define the API surface and models

- api/handle_decision.go
- api/scheduled_execution.go
- dto/decision_dto.go
- mocks/export_decisions_mock.go
- models/decision.go
- repositories/decisions_repository.go
- repositories/migrations/20240425140600_decisions_pivot_index.sql
- repositories/migrations/20240425161100_rationalize_decisions_indexes.sql
- usecases/case_usecase.go
- usecases/decision_usecase.go
- usecases/scheduled_execution_usecase.go
- usecases/scheduledexecution/export_schedule_execution.go
Add a new possibility to filter decisions by pivot_value in the API. Add an index on `decisions(org_id,pivot_value,created_at DESC)`.
Still as discussed here : https://www.notion.so/checkmarble/Defining-a-pivot-67cf95c5a94249fa95ba8c183e54751b.
I propose to wait a bit before we include this in the public API doc, on purpose.
--- 
The last commit is not directly related to this PR's subject, but cleans up indexes on the decisions table:
Before 
```
CREATE INDEX decisions_org_id_idx ON decisions(org_id uuid_ops,created_at DESC);
CREATE INDEX decisions_scheduled_execution_id_idx ON decisions(scheduled_execution_id,created_at DESC);
CREATE INDEX scenario_id_idx ON decisions(org_id,scenario_id,created_at DESC);
CREATE INDEX outcome_idx ON decisions(org_id,outcome,created_at DESC);
CREATE INDEX …
```
> query decisions by pivot value

- dto/data_model_pivot.go
- usecases/data_model_usecase.go
**The issue :**
When sending this HTTP request, an internal error is raised
```
POST /data-model/pivots
{
"base_table_id": "476e49fe-8d08-4c35-9dd5-6abd6a028527",
"field_id": "74114c55-7fb7-43e6-9867-34162b72827a"
}
```
Before the fix, it was required to always send `path_link_ids` in the payload, even for "field" pivot (= no need for links)
> fix(dto): handle optionnal path_link_ids

- models/transfer_check.go
- repositories/ingested_data_read_repository.go
- repositories/ingested_data_read_repository_test.go
- usecases/transfer_check_usecase.go
- avoid the issue where if the decision fails, we can't post it to transfercheck again
- cast fo float8 in aggregate query to allow aggregates with integers (esp. for pre-aggregated table for transfercheck)
- fix error condition on transfercheck adapter
> small fixes for transfercheck

- docker-compose.yml
- models/data_model.go
- repositories/ingestion_repository.go
Currently we end up with this in the query insights
we may still have duplicates corresponding to different numbers of rows to ingest, but it should be a lot better
> fix: sort columns when reading data model columns, for consistent ingestion queries

- jobs/execute_all_scheduled_scenarios.go
- jobs/scheduler.go
- main.go
- router.go
- tracing/tracing.go
- usecases/scheduledexecution/run_scheduled_execution.go
This PR adds tracing to scenario execution done in batch (rather than on API requests).
I had to reshuffle how we setup the tracer a bit, though some more work remains for another day (see comment below). 
Let's put this in staging and see how it behaves.
> tracing: inject dependencies instead of using otel globals

- dto/scenarios.go
- models/scenarios.go
- repositories/dbmodels/db_scenario.go
- repositories/migrations/20240507140800_scenario_workflow_type.sql
- repositories/scenarios_write.go
- usecases/scenario_usecase.go
- usecases/scenario_usecase_test.go
- new field `decision_to_case_workflow_type`, not nullable, `"DISABLED"` by default
- can be set to `"CREATE_CASE"` or `"ADD_TO_CASE_IF_POSSIBLE"` to activate the workflows. Doing so requires `decision_to_case_inbox_id` and `decision_to_case_outcomes` to be non null (and non empty in the case of `decision_to_case_outcomes`)
> API interface to edit scenario workflow

- usecases/scheduledexecution/run_scheduled_execution.go
What was happening is that in some cases (trigger mismatch, specifically) we never called span.End() (or at least we did so very late, because the deferred call was happening at the end of the batch execution). So we are seing some long spans towards the end of the batch execution (see screenshot).
TBH I still don't understand why they are not even longer - though probably the explanation is that there are many such long spans, all with deferred .End() queued, and the most recent ones are simply ended first when the function ends, and after a certain number the trace collection rate limiting kicks in (otherwise we'd see spans minutes old)
Anyway, I fix this by doing the span generation and scenario execution in a closure so that the deferred End does not wait forever.
> fix: span was leaking, leading to long traces

- jobs/execute_all_scheduled_scenarios.go
- jobs/execute_with_monitoring.go
- jobs/ingest_data_from_csv.go
- jobs/schedule_due_scenarios.go
- jobs/scheduler.go
- main.go
I spent some time trying to find exactly what kind of error this should be. After failing, I went for stupid string matching 🤷 
Edit 24/05: Ok while I was at it I also took the opportunity to add sentry monitoring and tracing to the other jobs, with a helper function to avoid repeating all the code
> try to silence sentry errors when cloud run fails to create unix socket

- repositories/case_contributor_repository.go
This should be sufficient for now.
The implementation is not perfect because it could result in a state where one of the concurrent transactions (the one that had the conflict) commits, the other one (without the conflict) does not, and we are left without the case contributor inserted.
But I think the completeness of case contributors is not the highest level of criticity and it's still really unlikely to happen anyway, so let's go with this for now.
Cf Bard's explanation below (trying to confuse me FFS)
> fix: conflict on case contributors insert should not return an error

- .env.example
- .vscode/settings.json
- dto/transfer_check.go
- integration_test/init_test.go
- main.go
- models/global_configuration.go
- models/transfer_check.go
- repositories/gcs_repository.go
- repositories/repositories.go
- repositories/transfercheck_enrichment.go
- usecases/transfer_check_usecase.go
- usecases/usecases_with_creds.go
Overall I'm satisfied with this PR as it is.
It expects to find a set of csv files in the transfercheck bucket on GCS, containing ip ranges. At the first transfercheck request received by the instance, they are read and put in memory. For an incoming sender ip address, we do a dichotomy search on the known ip ranges to find if it matches a given country/vpn/tor address range.
Because the GCS files are downloaded at the first request, that means we have a bit of a cold start (e.g. ~1sec on the first request) on the instance for transfercheck routes. But so be it, the possible workarounds are just too cumbersome compared to what we lose, for now anyway.
- implement an expiry date on the data held in memory, preparing for...
- ... refresh the files on GCS on a schedule (daily at least?) with …
> WIP: implement data enrichment for ip addresses on transfercheck

- api/handle_custom_list.go
Small breaking change to harmonize api return.
NB: I checked the frontend repo, the return type is not used. Indeed, the repository implementation is **wrong** so it would not work if used.
> fix(api): harmonize custom list return

- api/handle_license.go
It turns out a patter like `foo/*bar` parses the param value `"/bar"` if called with `foo/bar`...
There was an issue but the PR linked never went anywhere because breaking.
I quick fixed it this afternoon by inserting a duplicate of the key with the added slash in the db.
> fix error on parsing license key url param

- .env.example
- go.mod
- utils/context_logging.go
- utils/logging.go
[this](https://github.com/jussi-kalliokoski/slogdriver/blob/main/handler.go)
Also see [this](https://cloud.google.com/trace/docs/trace-log-integration#:~:text=To%20associate%20a%20log%20entry%20with%20a%20trace,project%20ID%20and%20TRACE_ID%20is%20the%20trace%20identifier)
~This means I need to put back the env var in cloud run~ or maybe not, see second commit
Goes with https://github.com/checkmarble/terraform/pull/27
> better logging in gcp env: log trace ids & spanid in logs so that we can correlate logs

- cmd/batch_ingestion.go
- cmd/run_job_scheduler.go
- cmd/schedule_scenarios.go
- cmd/scheduled_executor.go
- cmd/server.go
- integration_test/init_test.go
- repositories/repositories.go
In this PR, a refac to fix the issue with local use of fake GCS repository :
- need to handle fake GCS repository in `NewRepositories`
- refactor interface to use the `With*` options pattern, so we no longer need to explicitly assign "null" values for non used options in init phase
> refactor(repositories): add options pattern to NewRepositories

- api/handle_webhooks.go
- dto/webhooks.go
- repositories/convoy_repository.go
- usecases/webhooks_usecase.go
Small refactoring to be closer to other resources exposed on the API :
- POST and PATCH should return data
- Only return webhook secret on POST (closer to what we have on API_KEYS, it will help in case we want to implement finer permission strategy)
NB: currently there is no way to retrive an existing webhook secret but it's possible (the secret is stripped off at the dto adapter layer). I let this work for another iteration, focused on secret management.
> refactor(webhooks): refactor webhook dtos

- go.mod
- go.sum
- pure_utils/strings.go
- pure_utils/strings_test.go
- usecases/ast_eval/evaluate/eval_fuzzy_match.go
- usecases/ast_eval/evaluate/eval_fuzzy_match_test.go
Library replaced for licensing reasons. https://github.com/adrg/strutil which comes as a partial replacement (for the edit distance) is under MIT license.
--- 
Last thing to do (but no strong urgency): update the naming of the functions in the front and the doc. I changed "token_set_ratio" it to "bag_of_words_similarity" because it's less library specific and ultimately more self-explanatory, though I kept backwards compatibility of course for old ASTs.
--- 
Making if fully backwards compatible was a bit tricky because of subtle differences in how the Levensthtein distance is defined (and computed), see comment in the strings.go file
> remove go-fuzzywuzzy dependency

- api/handle_decision.go
- integration_test/scenario_flow_test.go
- usecases/decision_usecase.go
- usecases/transfer_check_usecase.go
This is a bit of a dirty fix.
I should probably start to disentangle the decisions usecase from the transfercheck usecase.
I'm creating a task in the linear backlog for this.
> dirty fix: no webhooks for decisions from TC usecase

- models/webhook.go
- repositories/convoy_repository.go
- repositories/webhook_events_repository.go
- usecases/usecases_with_creds.go
- usecases/webhook_events_usecase.go
Do retry count update properly:
- don't lose the number when the webhook finally goes to "success" (was being reset to 0)
- don't use needless DB transaction (instead, do the update in an atomic DB update, that cannot overwrite a row that is already in "success" by design, with a more specialized db update repository method
> refactor: properly do webhooks retry count

- api/handle_snoozes.go
- api/routes.go
- dto/case_event_dto.go
- dto/rule_snoozes.go
- models/case_event.go
- models/rule_snoozes.go
- models/webhook.go
- repositories/dbmodels/db_rule_snooze.go
- repositories/migrations/20240808165800_rule_snoozes_store_decision_id.sql
- repositories/rule_snoozes.go
- usecases/case_usecase.go
- usecases/rule_snoozes.go
- usecases/security/enforce_security_snoozes.go
- usecases/usecases_with_creds.go
Comment related to commit [01e9abe](https://github.com/checkmarble/marble-backend/pull/643/commits/01e9abed43b401c790254e9ebca483685f4fa4cf):
The field is nullable, for the odd case where we end up deleting decisions but do not want to delete all the related rule_snoozes. It shouldn't happen too much in theory but I already had the case once or twice with S&P where they wanted some decisions deleted.
I made it “on delete set null" instead.
> case event: rule snooze created

- dto/rule_snoozes.go
- models/rule_snoozes.go
- repositories/dbmodels/db_rule_snooze.go
Samll refactoring to enforce `created_from_rule_id` is defined (based on PR discussion #646)
(I'll merge this but to keep you in the loop, I tag your account)
> refactor(dto): change created_from_rule_id to be non-optionnal

- .gitignore
- api/api.go
- api/handle_datamodel.go
- integration_test/batch_ingestion_and_execution_test.go
- integration_test/generate_usecases.go
- integration_test/init_test.go
- integration_test/scenario_flow_test.go
- jobs/generate_usecases_with_creds.go
- mocks/data_model_repository.go
- models/pagination_and_sorting.go
- repositories/data_model_repository.go
- usecases/data_model_usecase.go
- usecases/data_model_usecase_test.go
- usecases/usecases_with_creds.go
- usecases/webhooks_usecase.go
- rework integration test suite: stop test if an error is met (instead of continuing & generating lots of noise) + some cleanup
- the whole test suite is starting to be a bit messy, but then again it's pretty efficient in terms of code coverage tested / code written (especially targetting the critical workflows)
--- 
It's not perfect yet, but it's starting to look not bad. I think we could rewrite it a bit to make it more modular and avoid the "test all the things in one big function and it becomes intractable", instead testing feature by feature. But I'm rather happy with the level of core logic coverage this gives us (excluding the api layer and TC, that is), so let's first roll with this.
> Test rule snoozing

- go.mod
Changes from a `go mod tidy` run on `main`
> chore(go.mod): remove mergo from go.mod

- api/handle_ingestion.go
- api/routes.go
- dto/upload_log_dto.go
- integration_test/batch_ingestion_and_execution_test.go
- jobs/ingest_data_from_csv.go
- mocks/upload_log_repository.go
- models/upload_log.go
- repositories/dbmodels/db_upload_logs.go
- repositories/migrations/20240829121800_upload_log_rows_ingested.sql
- repositories/upload_log_repository.go
- usecases/ingestion_usecase.go
Goes with https://github.com/checkmarble/marble-frontend/compare/pascal/mar-621-batch-job-data-ingestion-correctly-sets-status-in-error-case?expand=1
--- 
The motivation is here https://checkmarble.slack.com/archives/C05VAKSTL02/p1724747857435739
I ended up manually correcting upload log statuses in the db when there were errors.
In a next step, we could add mailing or other alerting to the users - but this is a good first improvement.
I'll do something similar for the scheduled execution (or at least make sure it doesn't remain in "processing" when the cloud run job times out).
---
I set a 1h timeout on the ingestion job (the cloud run job itself has a 2h timeout) which should be super sufficient (we'd be limited by the timeout of the file upload well before that).
--- 
I also added a …
> set status of batch ingestion job to failed if errors occur (including 1h timeout)

- README.md
Small update on the Readme (since I struggled to update FB emulator to the latest version)
**Note:** to properly uninstall Firebase, you can run :
```sh
curl -sL firebase.tools | uninstall=true bash
```
> docs: Update README.md for Firebase Emulator

- .vscode/settings.json
- Dockerfile
- go.mod
I think I managed to fix the dlv-dap timeout issue when launching code in VSCode. See my answer on SO: https://stackoverflow.com/questions/68753251/couldnt-start-dlv-dap/78967126#78967126
I also ended up bumping my version of go in the process => this PR.
> bump go version to 1.23.1

- repositories/migrations/20240910221600_decision_rules_org_id_idx.sql
Options to explore in the longer term for more efficient org deletion even if there are many decisions: use SET NULL instead of DELETE on CASCADE.
But for now this should do.
_Pour la forme_, I'll add a notice in the release note to run the migration manually before upgrading to the new version of marble, as it can be a slow one to run if there are many decision_rules.
> create indexes for better perf on org deletion

- repositories/case_repository.go
According to my tests, this should do the job. Postgres was not using the existing secondary index (indeed could not use it) because I was not filtering on decision org_id.
> improve query to use index

- api/handle_decision.go
- integration_test/scenario_flow_test.go
- models/decision.go
- repositories/analytics_views/decision_rules.sql
- repositories/analytics_views/scenario_iterations.sql
- repositories/dbmodels/db_decision_rule.go
- repositories/decisions_repository.go
- repositories/migrations/20240925120000_decision_rules_toast_setting.sql
- usecases/decision_usecase.go
- usecases/transfer_check_usecase.go
- Better setup of TOAST for decision_rules: storage of decision rule exec detail is dominating and it's bloat (see [postgres doc](https://www.postgresql.org/docs/current/storage-toast.html), [slack discussion](https://checkmarble.slack.com/archives/C04JB5ZADBN/p1727257822435979))
- Do not store the rule execution details for TC scenario executions (in the longer term, move to a blob storage, see [slack discussion](https://checkmarble.slack.com/archives/C04JB5ZADBN/p1727257822435979))
- Normalize decision_rule name & description - we are never filtering by them, they have no business being denormalized
- I also modified the sql questions in Metabase accordingly - though right now they're broken anyway because of the big decision_rules table
> set TOAST_TUPLE_TARGET for decision_rules + no exec detail on TC

- .vscode/launch.json
- api/handle_scheduled_execution.go
- api/routes.go
- dto/scheduled_scenario_executions.go
- integration_test/batch_ingestion_and_execution_test.go
- models/scheduled_scenario_executions.go
- repositories/dbmodels/db_decisions_to_create.go
- repositories/dbmodels/db_scheduled_executions.go
- repositories/ingested_data_read_repository.go
- repositories/migrations/20241002123300_reworked_batch_execution.sql
- repositories/scheduled_executions.go
- usecases/scheduled_execution/run_scheduled_execution.go
- usecases/scheduled_execution/schedule_scenarios.go
- usecases/usecases_with_creds.go
In this PR:
- the ids of (ingested) objects on which we want to take decisions are written to the DB ahead of creating the decisions
- the details of every object is only read when we actually create the decision on it
- decisions are then created one by one, each one in its own transaction, until an error encountered or all decisions have been created
- at the end, the scheduled execution is updated with its final status (can now be `"partial_failure"`) and with:
- the number of decisions that were planned to evaluate
- the number of decisions that have actually been evaluated
- the number of decisions that have been created (trigger condition match & no error)
- intermediate "decisions waiting to be created" are written to their own table, and their status is updated when they are …
> WIP: rework batch execution

- api/handle_liveness_probe.go
- api/routes.go
- repositories/liveness.go
- usecases/liveness.go
- usecases/usecases.go
If the liveness call does not at least call the DB, it's kind of useless
> liveness check calls the db

- api/handle_ingestion.go
- api/routes.go
- cmd/batch_ingestion.go
- cmd/run_job_scheduler.go
- cmd/server.go
- integration_test/api_end_to_end_test.go
- integration_test/init_test.go
- integration_test/scenario_flow_test.go
- repositories/blob_repository.go
- repositories/ingestion_repository.go
- usecases/case_usecase.go
- usecases/ingestion_usecase.go
- usecases/usecases.go
- usecases/usecases_with_creds.go
We can now ingest objects by batch. The number of max items in a batch is set to 100 by default and in our SaaS offering, but can be customized by on-premise customers if it makes sense for them, by setting the `"BATCH_INGESTION_MAX_SIZE"` env variable.
---
Renamed some variables/object properties that still contained "GCS" instead of "URL"
---
Tested with https://github.com/checkmarble/marble-backoffice/pull/29 and with a test case in the end to end test.
> ingest by batch via API

- repositories/ingested_data_read_repository.go
- repositories/scheduled_executions.go
- usecases/scheduled_execution/run_scheduled_execution.go
See https://checkmarble.slack.com/archives/C04JB5ZADBN/p1728377329077489
It turned out that the initial implementation was failing for large-ish numbers of decisions to create:
- because the memory usage was of the order of 10+ times the memory needed to store the list of object_ids on which we want to create the decisions (due to unnecessary allocations and passing big arrays of values (not slices) as function params)
- because in any case, postgres will only allow 65535 (an int16 worth of) parameters in a given exec statement - you can create more rows at a time, but then you can't pass the values as params, they must be hard coded in the query)
---
Note: we could also improve memory usage by starting to use proper uuid types for uuids instead of passing them around as strings, which …
> improvements on memory handling for batch exec

- dto/openapi.go
- specs/public_api.yaml
- add the doc for batch ingestion API
- to our API page in the app
- on the docs.checkmarble.com Api reference page
- also add the (missing) doc for "create all decisions on a payload" endpoint
----
See the doc page: https://docs.checkmarble.com/reference/post_ingestion-object-type-multiple
----
**Multiple ingestion api**
**Create all decisions API endpoint**
**Create all decisions endpoint return schema**
> doc: batch ingestion on api page

- models/decision.go
- repositories/analytics_views/decisions.sql
- repositories/dbmodels/db_decision.go
- repositories/decisions_repository.go
- repositories/migrations/20241015171200_fields_and_constraint_cleanup.sql
- repositories/organization_repository.go
- usecases/decision_usecase.go
- usecases/decision_workflows/decision_workflows.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/organization_usecase.go
- dropping constraints and indexes on the decision_rules table - it's the highest point of charge on the db and adding latency to transfercheck, for no good reason
- also removing a useless re-read of decision if it has not changed in the decision usecase (keeping it to read the case if it has been added, could be done more efficiently but I mostly want it to be faster in the transfercheck case for now).
- removing some deprecated fields
> db schema cleanup, remove constraints & indexes on decision_rules

- repositories/migrations/20241015171200_fields_and_constraint_cleanup.sql
TL:DR:
We create views independently of the main migrations (see the `repositories/analytics_views` folder), but they create dependencies which prevent us from modifying/removing fields that they use in the main migrations.
This is not visible when running the migrations from 0, and I think I fixed it manually without realizing this was breaking the order of operations when I ran it in my local DB.
I think we can find a more long-term solution when we start serving the analytics tool from a BQ replica of the DB rather than from a schema on the main db replica.
> fix: the migration was broken because of independently created views

- go.mod
- repositories/ingested_data_read_repository.go
- repositories/ingested_data_read_repository_test.go
The bug I'm trying to fix is the following:
When we execute the "db field read" operator, say with the params defined as in the screenshot below, meaning `trigger_table=table_a, path = [table_b, table_c, table_b_loop]` (those are the link names), the query that is generated essentially does `select table_b.field_name from table_b join table_c join table_b`.
Now, this logic works fine if every table appears only once, but the generated SQL is ambiguous if a table name appears several times. So I need to alias them.
I could rework this to alias them like `"table_b_1", "table_c_", ...`, but at the end of the day this would never be visible except to some extent in tracing data on DB queries - and even there it's not so interesting, because this query is never expected to be a DB perf …
> v1: it works (but ugly naming & cleanup to do)

- models/decision.go
- repositories/decisions_repository.go
Inserts of decisions and decision rules are still slower than I'd like them to be.
I tried some things already but that didn't quite work.
I'd like to try this, using (ordered by time) v7 uuids for better data locality in indexes. See [link](https://www.percona.com/blog/uuids-are-popular-but-bad-for-performance-lets-discuss/) for discussion.
NB: this means dropping the assumption, that we have anyway not applied on all tables since a while, that we do uuids with a shared prefix for all ids in a given org. But that's fine as this wasn't really useful in the end.
> try uuid v7 for better data locality in index

- .github/workflows/deploy_production.yaml
- .github/workflows/deploy_staging.yaml
- models/scheduled_scenario_execution_test.go
- models/scheduled_scenario_executions.go
- usecases/evaluate_scenario/evaluate_scenario.go
I learned something new on how pgx works, it first runs a prepare statement on all queries (by default) where the query is parsed but the parameter values are not used. Hence, pg is not able to parse `CONCAT('str_a', $1, 'str_b')` because it can't know the type of $1 which will only be known at query runtime.
In other situations, pg is able to infer the type, for instance if operators like `=` are used.
The recommended fix is to add type hints where query is possibly ambiguous.
In practice, this error was happening if the right-hand side of the equation contained a constant (it works with a field identifier).
> fix: typehint to let postgres prepare statement

- api/present_error.go
- usecases/transfer_check_usecase.go
Goal of this PR: make those error messages go away.
To be clear they do deserve monitoring, but not in this format.
> fix: better error handling on transfercheck

- api/routes.go
- models/pagination_and_sorting.go
- returning the total count of rows when filtering decisions is fundamentally broken and we need to get rid of it (as well as returning the "item index" on the returned decisions), as already previously discussed
- even if we apply a "limit 9000" (now limit 1000 after this PR), depending on the filters used, we can have pathological cases where the count gets dramatically slow, especially when the data is not in memory cache by the DB
- this PR is a temporary workaround that makes the app less broken, but it's not a full fix
--- 
What's happening here, for S&P, is the following:
- listing all decisions works fine, the count will stop after scanning 9000 rows, responds fast
- when applying a filter "outcome=approve", pretty much the same thing happens, they have ~500k decisions, almost all …
> temp workaround: make decisions filtering less broken

- usecases/ast_eval/evaluate/evaluate_custom_list_values.go
Fixes this sentry issue, which looks like a "list not found" but is actually a timeout
https://checkmarble.sentry.io/issues/6053673843/?environment=production&project=4506439156236288&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
> bugfix: bad error message when timeout

- dto/decision_dto.go
- integration_test/scenario_flow_test.go
- models/ast/ast_node_evaluation.go
- repositories/ingested_data_read_repository.go
- usecases/ast_eval/evaluate/eval_comparaison.go
- usecases/ast_eval/evaluate/eval_comparaison_test.go
- usecases/ast_eval/evaluate/eval_contains_any.go
- usecases/ast_eval/evaluate/eval_equal.go
- usecases/ast_eval/evaluate/eval_fuzzy_match.go
- usecases/ast_eval/evaluate/eval_not.go
- usecases/ast_eval/evaluate/eval_not_equal.go
- usecases/ast_eval/evaluate/eval_string_contains.go
- usecases/ast_eval/evaluate/eval_string_in_list.go
- usecases/ast_eval/evaluate/evaluate_aggregator.go
- usecases/ast_eval/evaluate/evaluate_arithmetic.go
- usecases/ast_eval/evaluate/evaluate_arithmetic_divide.go
- usecases/ast_eval/evaluate/evaluate_boolean_arithmetic.go
- usecases/ast_eval/evaluate/evaluate_boolean_arithmetic_test.go
- usecases/ast_eval/evaluate/evaluate_database_access.go
- usecases/ast_eval/evaluate/evaluate_filter.go
- usecases/ast_eval/evaluate/evaluate_read_payload.go
- usecases/ast_eval/evaluate/evaluate_time.go
- usecases/ast_eval/evaluate/evaluate_time_arithmetic.go
- usecases/ast_eval/evaluate/evaluate_time_arithmetic_test.go
- null values "bubble up" the AST of rule execution
- basically any operator that gets a nil value in one of its expected children, returns nil to its parent
- by exception, a series of `OR` (resp `AND`) returns `true` (resp. `false`) if it is "the obvious thing to return" (`true OR NULL = true`... see code)
- `isEmpty` operator coming soon in another PR
- a rule returns a `models.ErrNullFieldRead` error if a null value reaches the "top" of the AST
> ⚠️  An aggregation operator now returns nil if at least one filter value is nil, where it previously returned an error. As a consequence, depending on the other conditions in OR above, a rule may now return a hit where it returned an error previously. This is technically a breaking change but seems closer to what people should expect.
--- …
> first batch: allow to use null values in the AST, and return them as an error at the top level if null bubbles up

- dto/func_attributes_dto.go
- models/ast/ast_aggregator.go
- models/ast/ast_filter.go
- models/ast/ast_function.go
- models/scheduled_scenario_execution_test.go
- models/scheduled_scenario_executions.go
- usecases/ast_eval/evaluate/eval_is_empty.go
- usecases/ast_eval/evaluate/eval_is_empty_test.go
- usecases/ast_eval/evaluate_environment.go
- usecases/scheduled_execution/batch_filtering.go
- usecases/scheduled_execution/batch_filtering_test.go
Goes with PR https://github.com/checkmarble/marble-frontend/pull/602 on the frontend.
Implements the IsEmpty and IsNotEmpty operators, but only on the main AST (not for aggregator filters).
The operator returns true if the value is NULL or empty string, else false.
Also remove the unused and badly defined `NumberOfArguments` property of FuncAttributes (previously returned by the API used by the front for the list of operators). The source of truth for this is in the implementation of `Evaluate` for each function in `ast_eval`.
Tested on unit decisions with API, also tested that the batch run still works with isEmpty operators in the trigger condition (to test the SQL pre-filter)
Nb: the same filter for aggregates has voluntarily not been implemented now (mostly because I think it's less …
> implement isEmpty, isNotEmpty operators

- models/role.go
- usecases/security/enforce_security_user.go
- usecases/user_usecase.go
Transfercheck user creation was broken in the last refactor of the create user usecase permissions.
> fix permissions: create transfercheck user

- api/routes.go
- go.mod
- go.sum
The TL:DR is that gin-contrib.timeout [uses a goroutine internally](https://github.com/gin-contrib/timeout/blob/master/timeout.go#L49), which can cause weird ass bugs when a request continues to execute things and starts reading a context that is now another requests'.
vearne.gin-timeout avoids this by [starting off by deep-copying the gin context](https://github.com/vearne/gin-timeout/blob/master/timeout.go#L35) before doing anything else. 
---- 
copilot chat approves:
> replace timeout middleware

- .env.example
- repositories/ingestion_repository.go
- repositories/organization_schema_repository.go
Two goals in one step:
- use uuid v7, which we've seen has better write performance
- don't rely (at the db schema level, even if it's not used in the code in practice) on the uuid extension - it was added on the marble schema, now that I've migrated the clients org to another DB it prevents me from removing the marble schema (unused on that db) because it depends on the extension.
> use client-side uuidv7 for ingested objects

- repositories/data_model_repository.go
- usecases/data_model_usecase.go
- usecases/data_model_usecase_test.go
Of course handling of non-such formatted names remains, for existing data models & scenarios. But make our life easier in the long term by enforcing this on new names.
See also https://github.com/checkmarble/marble-frontend/pull/608 for frontend enforcing
> table,field,link name match ^[a-z]+[a-z0-9_]+

- models/rule.go
- repositories/dbmodels/db_rule.go
- repositories/migrations/20241203135200_scenario_rules_stable_id.sql
- repositories/rules.go
- usecases/scenario_iterations_usecase.go
Introduce a new stable rule id on rules, that identifies a rule throughout its successive versions.
> NB: the "snooze_group_id" that exists on rules already implements some of the properties below, but not all of them and it has its own usage anyway (even if we discussed creating this generic "stable rule id" back when we worked on snoozing this summer).
1. A newly rule acquires a new stable id
2. Existing rules (created prior to the release) don't have one for now, though see point 3 below
3. When a new draft is created from an existing version, new stable ids are generated for the rules in its existing version (and applied on their copies in the new draft)
4. A rule that is cloned takes a new stable id
5. In the future, we may backfill random stable rule ids for all old rules (with the …
> introduce stable rule id on rules

- api/handle_cases.go
- api/handle_decision.go
- api/routes.go
- dto/case_dto.go
- dto/decision_dto.go
- dto/pagination.go
- integration_test/batch_ingestion_and_execution_test.go
- models/case.go
- models/decision.go
- models/pagination_and_sorting.go
- repositories/case_repository.go
- repositories/dbmodels/db_case.go
- repositories/dbmodels/db_decision.go
- repositories/decisions_repository.go
- specs/public_api.yaml
- usecases/case_usecase.go
- usecases/decision_usecase.go
Loosely inspired from https://github.com/checkmarble/marble-backend/pull/764, and prerequisite for https://github.com/checkmarble/marble-frontend/pull/617.
- refactoring of the pagination model & dto (to better enforce at a higher level "now raw user input makes it into a sql query"
- the cases, decision list endpoints no longer return a total count (**breaking change**)
- the cases, decision list endpoints pagination input no longer accepts a `previous` or `next` (boolean) query params input when passing an `offset_id`. Instead, "`next`" type pagination is used by default (**breaking change**)
- the public endpoint for decisions no longer returns the `start_index`,`end_index` for a given page of items (**breaking change**)
- the list case and decision endpoints return a `has_next_page` …
> update cases & decisions list dto: no more count, return has_next_page

- repositories/migrations/20241218115400_improve_decisions_indexes.sql
I'm not entirely sure if that fixes the issue completely, but it think it should help greatly.
We can't force the indexes that postgres uses, and sometimes it's really painful.
Here in prod, because a very low proportion of decisions actually have a case_id not null, it's not choosing the use the index I want (decisions_by_org_id_index) but rather takes an index on (org_id, case_id) when I filter by "case_id not null"
> improvement: indexes for decisions listing

- api/handle_scenarios.go
- api/routes.go
- dto/scenarios.go
- models/ast/ast_function.go
- models/ast/ast_node_evaluation.go
- models/ast/evaluation_errors.go
- models/scenarios.go
- repositories/dbmodels/db_scenario.go
- repositories/migrations/20250102151657_case_name_template.sql
- repositories/scenarios_write.go
- usecases/ast_eval/evaluate/eval_string_template.go
- usecases/ast_eval/evaluate_ast_expression.go
- usecases/ast_eval/evaluate_environment.go
- usecases/decision_usecase.go
- usecases/decision_workflows/decision_workflows.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/scenario_usecase.go
- usecases/scenarios/scenario_and_iteration.go
- usecases/scenarios/scenario_validation.go
- usecases/scenarios/scenario_validation_test.go
- usecases/scheduled_execution/async_decision_job.go
- usecases/usecases.go
- usecases/usecases_with_creds.go
- Added StringTemplate ast evaluation
- Added a new column `decision_to_case_name_template` in scenario table
- Added new endpoint `/scenario/:scenarioId/ast-validation` to validate an AST node
- Updated case creation to evaluate its name with AST stored in `decision_to_case_name_template`
Frontend PR: https://github.com/checkmarble/marble-frontend/pull/647
> feat: case name templating

- models/aggregate_filter.go
- models/ast/ast_filter.go
- repositories/ingested_data_read_repository.go
- repositories/ingested_data_read_repository_test.go
- usecases/ast_eval/evaluate/evaluate_aggregator.go
- usecases/ast_eval/evaluate/evaluate_filter.go
- usecases/ast_eval/evaluate/evaluate_filter_test.go
- usecases/indexes/aggregate_query.go
Frontend PR: https://github.com/checkmarble/marble-frontend/pull/659
> feat: add is empty, is not empty, starts with, ends with filters operators

- integration_test/scenario_flow_test.go
- models/ast/ast_function.go
- pure_utils/map.go
- usecases/ast_eval/evaluate_ast.go
- usecases/ast_eval/evaluate_ast_test.go
- usecases/ast_eval/evaluate_environment.go
- usecases/scenarios/scenario_validation.go
- usecases/scenarios/scenario_validation_test.go
This adds circuit breaking to boolean evaluation.
An AND boolean resolves to false if the first operand is false, and an OR boolean resolves to true if the first operand is true. With this, second operands and skipped if they can have no sway on the node's result.
Circuit breaking is disabled when trying to validate a scenario, so all cases are considered.
> AST: Lazy evaluate boolean child nodes.

- models/ast/ast_aggregator.go
- models/ast/ast_custom_list_attr.go
- models/ast/ast_function.go
- models/ast/ast_node.go
- models/ast/ast_node_evaluation.go
- models/ast/ast_node_weight_test.go
- models/ast/node_evaluation_dto.go
- usecases/ast_eval/evaluate_ast.go
- usecases/ast_eval/evaluate_ast_test.go
- usecases/ast_eval/evaluate_environment.go
- usecases/ast_eval/weighted_nodes.go
- usecases/scenarios/scenario_validation.go
- usecases/scenarios/scenario_validation_test.go
This adds several things:
* Commutative functions are marked as such.
* AST functions now have an associated cost depending on their computational complexity.
* Evaluation will now reorder the children of a commutative node to execute the cheapest first.
This would have the benefit, thanks to the lazy evaluation of AST nodes (circuit breaking), to improve overall performance for those scenarii.
> AST: Allow children of commutative nodes to be reordered cost-wise.

- usecases/security/enforce_security_user.go
- usecases/security/enforce_security_user_test.go
There was an issue in the security enforcement for update user where an admin could not change a user's role except **to** `ADMIN`.
> Fix issue where an admin could not change a user's role except to ADMIN.

- .env.example
Rationale for changes:
* File is organized thus:
* Mandatory settings go at the top
* Then tuning settings
* Finally, optional settings most people will not touch
* Examples are given when value format is not obvious (database DSN or bucket URLs).
* If requiring external value, explain how to get the value.
* Internal settings not for end users are removed from the file
* All settings provide detailed explanation as to what value to set them
* When settings have alternatives, only one is present, the others are commented out.
* Try to avoid repeating the settings name as its only explanation.
> Improve example env file to act as proper documentation

- repositories/rules.go
- usecases/rules_usecase.go
The query optimizer was in some cases (at least: in the case where there are few phantom decisions) making a really bad decision on the execution plan for getting rule execution statistics on a test run, namely by planning a full table scan of decision rules.
In detail, I forbid hash joins, merge joins, and the reordering of joins for the query.
Sorry for the big empty space below the text, it seems this is an unexpected side effect of using the details tag in github markdown
Considering the query for getting rule execution stats on `(phantom_)decisions`, as below
```sql
select scir.stable_rule_id, scir.name, dr.outcome, scit.version, COUNT(*) as total
from  phantom_decisions as d (respectively decisions as d)
join scenario_iterations as scit ON scit.id = d.scenario_iteration_id
join …
```
> attempt to ensure a better query execution plan for test run stats by forbidding hash joins (and some others)

- repositories/decision_phantoms_repository.go
- usecases/ast_eval/evaluate_ast_expression.go
- usecases/decision_phantom/decision_phantom.go
- usecases/decision_usecase.go
- usecases/decision_workflows/decision_workflows.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
- usecases/evaluate_scenario/evaluate_sanction_check_test.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/scheduled_execution/async_decision_job.go
- usecases/scheduled_execution/async_scheduled_exec_status_job.go
- usecases/usecases_with_creds.go
Continued from https://github.com/checkmarble/marble-backend/pull/817 - dependency injection to the EvaluateScenario method(s) was becoming really cumbersome & error prone because "static" dependencies where passed around as function params rather than being injected from the usecase factory
One small change in actual code logic (added missing storing of sanction check in two places which I pointed out in comments), otherwise it's all just reshuffling injected dependencies and removing some unused dependencies
> rework evaluate scenario deps injection

- dto/sanction_check_dto.go
- models/sanction_check.go
- usecases/sanction_check_usecase.go
Before we merge the work in progress, let's add basic search term for the refinement endpoint before we start implementing the actual per-entity logic.
> Accept a generic search term when refining a sanction check.

- usecases/sanction_check_usecase.go
The only security enforcement we had on listing sanction checks was to check whether the user had permission to read or update the case. This fell flat when a decision was not yet added to a case.
This conditions the case permission checking on whether the decision is in a case, or otherwise checks that the user can read the decision.
> Fix permissions on list sanction checks

- usecases/scenarios/scenario_validation.go
We will still need to synchronize with the frontend to ensure how to properly transmit error information, but this at least blocks commit and publish.
> Check sanctions rules validation before committing and publishing.

- dto/sanction_check_refine_query_dto.go
- dto/sanction_check_refine_query_dto_test.go
Frontend used uppercased field names for those.
> Use uppercase fields on refine query search

- models/sanction_check.go
- repositories/fixtures/opensanctions/response_full.json
- repositories/fixtures/opensanctions/response_partial.json
- repositories/httpmodels/http_opensanctions_result.go
- repositories/opensanctions_repository.go
This implements Open Sanctions queries properly, since the API does return results that are not considered matches (whose score does not meet the `threshold`) if their score is between `cutoff` and `threshold`.
Right now, thus, we do not request the API to return non-matches (by setting the same value for the two parameters). Even though they are not returned, logic to filter them out and determine partial results was amended, in case we change the behavior in the future).
> Filter out returned results that are not matches.

- dto/sanction_check_config_dto.go
- dto/sanction_check_dto.go
- dto/scenario_validation_dto.go
- models/opensanctions.go
- models/sanction_check.go
- models/scenario_iterations.go
- models/scenario_validation.go
- repositories/dbmodels/db_sanction_check.go
- repositories/dbmodels/db_sanction_check_config.go
- repositories/dbmodels/db_sanction_check_match.go
- repositories/dbmodels/db_sanction_check_whitelist.go
- repositories/migrations/20250210144400_create_sanctions_whitelist.sql
- repositories/opensanctions_repository.go
- repositories/sanction_check_config_repository.go
- repositories/sanction_check_repository.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
- usecases/evaluate_scenario/evaluate_sanction_check_test.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/sanction_check_usecase.go
- usecases/sanction_check_usecase_test.go
- usecases/scenarios/scenario_validation.go
A sanction check config can now receive an AST to dynamically select the field uniquely identifying a record.
A sanction check match review can now include a boolean, `whitelist` that will permanently link an Open Sanctions entity ID to the unique identifier selected by the previously defined expression.
Any object/entity that has been whitelisted will not be excluded from a sanction check matches.
> Implement sanction check whitelists.

- models/opensanctions.go
- models/opensanctions_test.go
- usecases/sanction_check_usecase.go
This builds on the feat/sanctions/name-recognition branch (to take advantage of the multi-query model).
OpenSanctions does not let us match on `Vehicle` (and other "abstract" object types) directly. If we want ot refine on those, we need to normalize the queries by duplicating the requests accordingly.
> Adapt non-matchable object types to multiple queries in refines.

- api/handle_decision.go
- api/handle_ingestion.go
- api/routes.go
- dto/api_error.go
- dto/openapi.go
- integration_test/scenario_flow_test.go
- mocks/enforce_security.go
- models/payload.go
- repositories/ingestion_repository.go
- repositories/ingestion_repository_test.go
- specs/public_api.yaml
- usecases/decision_usecase.go
- usecases/executor_factory/executor_factory_stub.go
- usecases/ingestion_usecase.go
- usecases/ingestion_usecase_test.go
- usecases/payload_parser/payload.go
- usecases/payload_parser/payload_test.go
- usecases/testing_helpers.go
- utils/uuid.go
Two new endpoints for ingestion, using the same path but with PATCH method. They allow the customer to send a partial object, and reuse missing values from a previously ingested version of the object. If some of the missing values are required and are not present in the previous version, or if it is the first time this object id is ingested, we get an error, otherwise a new version is ingested.
For instance suppose the data model is as such
```
object_id    required
updated_at   required
req          required
value        optional
```
If we receive 
```json
{
"object_id": "1",
"udpated_at": "2022-...",
"req": "ok"
}
```
we will look up a previous version with object_id "1" and update it by keeping the same `"value"`, or create a new object if no previous version exists.
If we receive …
> patch (upsert) endpoint for data ingestion

- dto/sanction_check_config_dto.go
- dto/scenario_validation_dto.go
- infra/opensanctions.go
- models/errors.go
- models/scenario_iterations.go
- models/scenario_validation.go
- repositories/dbmodels/db_sanction_check_config.go
- repositories/name_recognition_repository.go
- repositories/opensanctions_repository.go
- repositories/sanction_check_config_repository.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
- usecases/evaluate_scenario/evaluate_sanction_check_test.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/sanction_check_config_usecase.go
- usecases/scenario_publication_usecase_test.go
- usecases/scenario_publications_usecase.go
- usecases/scenarios/scenario_validation.go
- usecases/usecases_with_creds.go
Scenario should fail validation if:
* One of `query/name` or  `query/label` returns a non-string value (validation names `query_name` and `query_label`)
* Both `query/name` and `query/label` are unspecified (validation name `query`)
Scenario publishing should fail if:
* The Open Sanctions API is unreachable
Also added the logic for not executing name recognition if it is not configured. In that case, the configured label will be inserted into the main request as a `Thing`.
This also prevents scenario publishing if the OpenSanctions API is either not-configured or does not respond to healthchecks.
> Sanctions check scenario validation

- api/handle_scenarios.go
- usecases/scenario_usecase.go
- usecases/scenarios/scenario_validation.go
- /validate-ast was testing against bool if no expectedType, now it won't type check the returnValue
Frontend PR: https://github.com/checkmarble/marble-frontend/pull/697
> feat: make ast validation without type show no type error

- api/present_error.go
- dto/api_error.go
- infra/opensanctions.go
- models/errors.go
- repositories/opensanctions_repository.go
- usecases/scenario_publications_usecase.go
To be discussed, it might be interesting to settle on a common status code / error payload to inform the frontend that some preconditions failed on the backend, especially as far as third-party services are concerned.
Those errors could indicate that a specific class of error happened when trying to use a certain third-party service.
In this PR, the error looks like this:
```json
{
"message": "A required configuration was missing or invalid",
"details": {
"error": "missing API key for SaaS Open Sanctions configuration",
"reason": "missing_configuration",
"requirement": "open_sanctions"
},
"error_code": "missing_requirement"
}
```
Where both `details.requirement` and `details.reason` are enum variants:
```go
type (
RequirementError       string
RequirementErrorReason string
)
const ( …
```
> Create standard response for requirement misconfiguration.

- usecases/ast_eval/evaluate/eval_string_concat.go
- usecases/ast_eval/evaluate/eval_string_concat_test.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
The diff got kind of big, but the premise here is basically:
- opensanctions errors out (400) if it returns a query with only empty search inputs
- so we want to handle a search with empty string in the same way as null value read, on our side
- so I'm also making the concatenation ast node return an empty string if it receives no inputs (or only nil inputs). There could be a point to be made to return nil if it only receives nils ? but I'm not sure if it's worth it
> proposed changes on empty value handling for opensanctions search

- docker-compose.yml
A fix for issue https://github.com/checkmarble/marble-backend/issues/797.
I previously created a custom image that added pg_cron to postgres, but we no longer use it and my custom image was a pain for users not on arm architecture.
> use standard postgres 15 image in docker compose

- repositories/sanction_check_repository.go
- usecases/sanction_check_usecase_test.go
They are now ordered according to the following criteria:
- Confirmed hit first, then pending, then no match, then skipped
- Within those groups, higher scores are returned first
> Ordering of sanction check matches.

- api/handle_sanction_checks.go
- repositories/sanction_check_repository.go
- usecases/sanction_check_usecase.go
- usecases/sanction_check_usecase_test.go
Adds an endpoint to retrieve, if applicable, the initial sanction check for a decision, before refinements.
To be discussed if it is a separate endpoint or a parameter on the existing one.
> Initial (pre-refinements) sanction check endpoint

- .github/workflows/backend_deploy_workflow.yaml
GitHub Actions uses BuildKit with the Git Context to build container images. By default, it does not keep the `.git` directory in the used working copy. This means that, by default, we cannot use `git` commands to extract the current version of the software.
This adds a BuildKit build argument to keep the directory around.
> BuildKit: keep git directory to extract the version

- api/handle_scenario_test_run.go
- dto/scenario_testrun.go
Creating a test run had two issues related to the end date selection:
* The end date would always be at the start of the selected day, where instinctively, you would think that selecting an end date of "Feb 27th" would still allow the test run to continue on the 27th.
* The frontend sends us a time relative to the browser's locale, which may or may not be the same as the organization's set timezone. The "end of day" calculation must therefore be performed in the org's timezone, but from the selected date (the user's intent).
This PR sets the end date and time for a test run as the end of the selected day in the organization's timezone.
> Use correct end date for test run depending on org set timezone.

- .github/workflows/backend_deploy_workflow.yaml
- Dockerfile
BuiltKit only does a shallow clone, even when asked to copy the git directory, which means we cannot use tags to determine Marble's version.
This adds a previous step to export the version to an output, that is used as a build arg.
> Change version extraction to GitHub Actions output

- cmd/server.go
- cmd/worker.go
- integration_test/init_test.go
- integration_test/river_helpers.go
- integration_test/scenario_flow_test.go
- mocks/ingested_data_indexes_repository.go
- mocks/task_queue_repository.go
- models/concrete_index.go
- models/river_job.go
- repositories/ingested_data_indexes_repository.go
- repositories/pg_indexes/pg_indexes.go
- repositories/task_queue_repository.go
- usecases/indexes/index_editor.go
- usecases/scenario_publication_usecase_test.go
- usecases/scenario_publications_usecase.go
- usecases/scheduled_execution/index_cleanup_job.go
- usecases/scheduled_execution/index_creation_job.go
- usecases/task_queue.go
- usecases/usecases_with_creds.go
This is a prototype for using our workers and asynchronous tasks for various aspects of Marble maintenance or operational tasks. Examples of such tasks might include:
* Creation of database indices
* Cleanup of useless or invalid indices
* Notification sending
> Move index creation to an asynchronous worker

- repositories/sanction_check_config_repository.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
- usecases/scenarios/scenario_validation.go
This PR makes the sanction check config trigger rule optional by:
- Setting field in DB as NULL is there's not trigger condition or it is an Undefined AST Node
- Bypassing validation if the trigger is nil
- Not trying to execute the trigger if it's nil when evaluating the sanction check
Frontend PR: https://github.com/checkmarble/marble-frontend/pull/724
> feat: make trigger in sanctioncheck optional

- models/sanction_check.go
- usecases/sanction_check_usecase.go
See slack conv: https://checkmarble.slack.com/archives/C04J8MPJJHY/p1739981694748709.
Currently the frontend seems to allow to refine (basically redo) a sanction check that was in error status, but it is forbidden by the backend, resulting in an error displayed in the case manager.
The rationale is that late is better than never to perform a sanction check properly if it was originally an error. As of now, the only error case being that only empty inputs have been sent to the OS API.
> sanction check in error status can be refined

- cmd/worker.go
- mocks/task_queue_repository.go
- models/river_job.go
- repositories/opensanctions_repository.go
- repositories/task_queue_repository.go
- usecases/decision_usecase.go
- usecases/sanction_check_usecase.go
- usecases/scheduled_execution/match_enrichment_job.go
- usecases/usecases_with_creds.go
This also fixes an issue with overall enrichment where we replaced the payload completely (hence losing attributes specific to the search, e.g. `score`).
> Add async match enrichement 

- integration_test/scenario_flow_test.go
- repositories/ingestion_repository.go
- usecases/ingestion_usecase_test.go
Borrowing from the explanation comment in the PR:
```
// Try to only load the fields that are actually missing from the payloads (in the case of a partial update).
// The same method is used for the POST and PATCH endpoints, but if no fields are missing then there is a
// covering index on the object_id and updated_at columns that can be used.
// This makes the POST endpoint possibly faster to respond than the PATCH endpoint for ingestion (when there
// is data present and some payload have missing fields).
```
The PR that allowed partial payload ingestion (PATCH endpoints for ingestion) made changes that caused every ingestion call to always go read data from the base table (client data table), even though a covering index exists that is sufficient in many cases.
> chore: try to optimize for covering index for PATCH/POST ingestion

- cmd/worker.go
The repository for sanction checks was configured, but not the usecase.
Clearly a QA issue here, though I wonder if the repository/usecase configuration is becoming too complex/coupled in a hidden way.
> fix: batch exec with sanction was failing because a usecase config was missing

- repositories/decisions_repository.go
- usecases/decision_usecase.go
- usecases/scheduled_execution/test_run_summary_job.go
As far as I can tell, no change is necessary in in terms of the indexes that the query is expected to use.
We _could_ add an additional index on phantom decisions that also filters on scenario_id - but that can be done later if we see that the query remains slowish.
As a result, currently existing summaries are wrong, so I think i'll (manually) delete them and reset the "summarized" status on existing test runs.
> tentative fix: decisions by outcome stats are wrong due to missing filter

- repositories/scenario_testrun.go
- specs/public_api.yaml
- usecases/scheduled_execution/test_run_summary_job.go
The final release is going to be for tomorrow in the end.
There was a bit of a logic error related to the fact that the watermark is on the summaries, that no summaries are updated if no decisions exist in the window between [then, windowBound], where the code remains stuck (and a test run would remain unsummarized forever).
I fixed it by adding a "bump all watermarks after writing the summaries" step.
It was a bit of a pain to debug, because the issue would appear in a way that is very dependent on how the decisions on the scenarios are distributed in time.
> fixes on watermark logic

- usecases/decision_usecase.go
- usecases/ingestion_usecase.go
- Corrects an error on logic in the POST /decisions/all endpoint introduced in v0.38
- smuggled inside this PR too: small fix so that an ingestion job that times out (or context canceled for another reason) does not fail to update the batch ingestion's status
> fix bug on decision/all endpoint

- models/concrete_index.go
- repositories/ingested_data_indexes_repository.go
- repositories/pg_indexes/pg_indexes.go
- usecases/scheduled_execution/index_creation_job.go
See linear for the details on the bug that triggered the ticket.
The fix was a bit trickier than I initially thought, because of how the ConcreteModel index was also used as a dto implicitly when serializing the job a rgs.
Also takes care of https://linear.app/marble-eu/issue/MAR-802/review-placement-of-index-name-logic-following-incident-on-index following the incident yesterday.
> fix bug impacting index creation for test run

- usecases/decision_usecase.go
- usecases/scheduled_execution/async_decision_job.go
Corrects one of the last "big" causes of data mismatch between test run and live scenario.
The remaining ones are (but smaller magnitude - probably, at least in the nominal case):
- batch exec trigger condition precompute (see comment added inline)
- test run decisions are run in a gorouting, liable to error or timeout - we could do them in a task queue in the future it this proves too much of a problem
I tried two versions, one with a closure and the other with a dedicated private method in the usecase. The second is more DRY I guess but it takes an uncomfortable number of input params. Probably still better, I guess.
Most of the logic is still replicated where we do the async decisions for batch exec.
> fix: test runs phantom decisions were not created on the /decisions/all endpoint

- usecases/ingestion_usecase.go
- usecases/ingestion_usecase_test.go
- usecases/payload_parser/payload.go
- usecases/payload_parser/payload_test.go
This PR adds a new format supported in payloads and ingested data, which is the same format as `time.RFC3339` but without timezone information. The parsing still assumes the datetime is represented as UTC.
Also added tests that check the times parsed from ingestion.
> Handle timezone-less RFC3339 datetimes

- api/handle_scenarios.go
- dto/ast_validation_dto.go
- models/ast_validation.go
- models/scenario_validation.go
- usecases/scenario_usecase.go
- usecases/scenarios/scenario_validation.go
AST Validation was only return an evaluation and formula validation error were mixed with evaluation errors. Rework it to be like other validation processes (trigger, rules and sanction)
Frontend PR: https://github.com/checkmarble/marble-frontend/pull/746
> fix: fix errors management for ast validation

- repositories/name_recognition_repository.go
- repositories/opensanctions_repository.go
- usecases/scheduled_execution/index_creation_job.go
- usecases/scheduled_execution/match_enrichment_job.go
- usecases/usecases_with_creds.go
Two issues surfaced in the match enrichment job:
* It would still run if the server was properly configured with self-hosted Yente, but not the worker. We want to short-circuit execution in the worker in those cases.
* If the enrichment process had a response from OS but a failing status code, the unclosed body would cause a memory leak.
> Fix memory leak in match enrichment

- models/webhook.go
Bug notified by Gemba, updating the list of event types that should be dispatched was broken because of the mismatch in allowed values.
Problem: it seems that in a recent (?) version of convoy, the "Advanced Webhook Subscription" feature has been moved behind the paywall: https://www.getconvoy.io/pricing.
No big issue for our managed instance as I'm happy to pay for the license and let them apply restrictions on open source, but I'm a bit unhappy that this breaking change breaks some functionality for our self-hosted end users.
I'll add a warning on the UI to explain the option is limited to paying convoy users.
> fix: list of allowed webhook events was not consistent

- README.md
- mise.toml
- Start the database container only in `docker compose` command.
- Use the default firebase cli install script since it's now fixed.
- Propose the usage of [mise](https://mise.jdx.dev/) to ease the env vars export and create the its config file.
> chore(doc): Improve getting started section

- api/handle_snoozes.go
- dto/rule_snoozes.go
- integration_test/scenario_flow_test.go
- models/permission.go
- models/role_permission.go
- models/rule_snoozes.go
- pubapi/constants.go
- pubapi/response.go
- pubapi/tests/specs/v1/v1.go
- pubapi/v1/routes.go
- pubapi/v1/rule_snoozing.go
- pubapi/v1/sanction_checks.go
- pubapi/validator.go
- repositories/dbmodels/db_rule_snooze.go
- repositories/migrations/20250321221500_set_snooze_user_nullable.sql
- specs/v1_public_api.yaml
- usecases/case_usecase.go
- usecases/rule_snoozes.go
- usecases/sanction_check_usecase.go
- usecases/security/enforce_security_sanction_checks.go
- usecases/usecases_with_creds.go
This PR adds an endpoint to the public API to perform context-less, free-form searches for sanctioned entities. The first version does not allow for any configuration.
> Free-form sanctioned entity search + rule snoozing

- specs/v1_public_api.yaml
Small PR to fix errors on the public API v1 OpenAPI spec.
There is still a warning (body on `DELETE`), which has no semantics but is allowed with HTTP 1.1, so I unilaterally opt into ignoring it.
> Remove duplicated operation ID and formatting.

- pubapi/tests/specs/v1/sanction_checks.go
- pubapi/tests/specs/v1/whitelists.go
- pubapi/v1/routes.go
- pubapi/v1/sanction_checks.go
- specs/v1_public_api.yaml
To allow expanding sanction checks in the future (to include PEPs, for example) and avoid inconsitencies and breaking changes, let's rename it to "screening" and derivatives.
> Rename sanction checks in public API to transaction screening.

- api/handle_sanction_checks.go
- dto/sanction_check_dataset_dto.go
- models/opensanctions.go
- repositories/httpmodels/http_opensanctions_dataset_freshness.go
- repositories/opensanctions_repository.go
Before merging this, we need to understand tghe semantic behind `index_version`, should we say that we are up to date iof it is null or out of date?
> Handle null index_version for OpenSanctions datasets.

- api/handle_signup_status.go
- usecases/signup_usecase.go
This would be false if the orgs or users table do not exist, maybe indicating that migrations have not been run properly.
Ultimately, we could also maybe actually check if all migrations were applied, including after upgrades.
> Add migrations_run boolean to signup status.

- jobs/middlewares.go
- repositories/organization_repository.go
- usecases/decision_usecase.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/scheduled_execution/run_scheduled_execution.go
- utils/sentry.go
Better log when a panic is recovered.
See for instance
[slack](https://checkmarble.slack.com/archives/C063SMVJ4BY/p1743689992837139)
[sentry](https://checkmarble.sentry.io/issues/6505381706/?project=4506439156236288&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0)
Also fixes this sentry issue https://checkmarble.sentry.io/issues/6425972939/?project=4506439156236288&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=1
> better log on recovered panic

- integration_test/init_test.go
- models/concrete_index.go
- models/concrete_index_test.go
- repositories/ingested_data_indexes_repository.go
- repositories/migrations/20240124111516_create_analytics_schema.sql
- repositories/migrations/20241105143100_drop_analytics_schema.sql
- repositories/pg_indexes/pg_indexes.go
- repositories/pg_indexes/pg_indexes_test.go
- usecases/data_model_usecase.go
First commit
Index `(account_id DESC) INCLUDE (booked_at)` being created even though there is already an index `(account_id DESC, booked_at DESC, status DESC) INCLUDE (available_balance_after)`
=> Logic error in the "does an existing index cover our needs" logic
Second commit
See issue https://github.com/checkmarble/marble/issues/91
Index parsing is broken for escaped field names. I thought we wouldn't have any, because we (currently) don't escape field names when we create the tables (we probably should, in which case this is a good preparation PR). However, we still have escaped field names if reserver sql keywords are used as index names.
E.g. you can create a table 
```sql
create table test_idx_table (
id int primary key,
time time
);
create index test_idx on test_idx_table(id, time) …
```
> fix error where unnecessary indexes were being created

- models/ast/ast_filter.go
- repositories/ingested_data_read_repository.go
- usecases/ast_eval/evaluate/evaluate_filter.go
- usecases/ast_eval/evaluate/evaluate_fuzzy_match_options.go
- usecases/ast_eval/evaluate_environment.go
Continued from @siiick 's PR. Making some changes to make it work, and to decide on the final design.
(continuation of this PR, or the one it merges into)
- adapt list of algorithm names that are acceptable (won't be the same as for main ast fuzzy match)
- adapt proper score thresold (between 0 and 1 or 0 and 100?)
- finish writing proper logic for the final SQL query
- check that the examples of strings that we give, are still relevant for our final scoring logic
- adapt list of algorithm names that are acceptable (won't be the same as for main ast fuzzy match)
- adapt translations, view only component, and other visual stuff
> fixes: make fuzzy match on aggregate work

- .vscode/settings.json
- repositories/migrations/20240124111516_create_analytics_schema.sql
- repositories/migrations/20241105143100_drop_analytics_schema.sql
As discussed in slack: the user is not strictly required, in particular it's dropped since Nov 2024.
Worst case side effect of this migration would if if someone currently on a version of marble from between March 2024 and Nov 2024 upgrades to the most recent version, they would remain with an unused user "analytics" (without permissions on anything) => acceptable.
> chore: improve migrations by not making them create a postgres user

- api/handle_cases.go
- api/handle_inboxes.go
- api/routes.go
- dto/inbox_dto.go
- mocks/enforce_security.go
- mocks/inboxes_repository.go
- models/case_event.go
- models/inbox.go
- repositories/case_repository.go
- repositories/dbmodels/db_inbox.go
- repositories/inboxes_repository.go
- repositories/migrations/20250416151100_add_inbox_escalation.sql
- usecases/case_usecase.go
- usecases/inboxes/inboxes.go
- usecases/inboxes_usecase.go
- usecases/security/enforce_security_inboxes.go
This PR allows the configuration of an escalation inbox on an inbox. That inbox will be the target of the escalation event that will move a case there, unassign and unsnooze it, and boosts it so it is marked as waiting for event.
It also implements the endpoints used to configure the target as well as the one to trigger the event.
It adds a case event related to escalation.
> Implemented case escalation.

- repositories/opensanctions_repository.go
An undocumented "feature" of Cloud Run is that they reserve the `/healthz` path for internal purpose, meaning that the backend service will never get requests destined to that endpoint.
As we use that endpoint on Yente to check if it is up, this failed constantly with a 404 error.
This PR moves our healthcheck to `/readyz`, which is not reserved and serves - more or less - the same purpose.
> Change Yente healthcheck to /readyz

- usecases/scheduled_execution/async_decision_job.go
The testRunCallback can be nil without there being an error, because there is an early exit condition in handleDecision (if the scheduled execution status is "failure").
> fix panic on async decision exec for canceled scheduled execution

- repositories/migrations/20250506113500_remove_snooze_groups_cascade.sql
This removes the `on delete cascade` set on the snooze groups foreign key on the iteration rules tables, to guard against deleting rules when truncating live data.
> Remove cascade on iteration rules foreign key to snooze groups.

- mocks/enforce_security.go
- usecases/inboxes_usecase.go
- usecases/security/enforce_security_inboxes.go
This PR does two things:
- Allow access to inbox settings, not only to organization admins, but also to inbox admins. If a user is an admin for at least one inbox, they will see the inbox settings section and be able to update it and manage its users.
- Gate the scenarios settings behind being an organization admins. Until now, any user could see it and manipulate the form (even though the backend rejected the action).
This relates to checkmarble/marble-frontend#849.
> Change permissions to allow inbox admins to update inboxes.

- Dockerfile
Fix docker warning 
```
FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
> Fix docker case warning

- .github/workflows/backend_deploy_workflow.yaml
- .github/workflows/backend_test_workflow.yaml
So when using reusable workflows, Github actions expects us to set the permissions on the calling workflow (to actually grant permissions) and on the called workflow (to limit the maximum permissions that may be received).
This is newly detected by github CodeQL scanning.
If this resolves on the backend, I'll do the same on frontend.
> resolve github code scanning issue on CI

- .env.example
- .github/workflows/backend_deploy_workflow.yaml
- .github/workflows/deploy_production.yaml
- .github/workflows/deploy_staging.yaml
- Dockerfile
- api/configuration.go
- api/dependencies.go
- cmd/config.go
- cmd/server.go
- main.go
The gist of it is: stop passing the segment key around as cleartext env var shared with customers (even though it's still accessible for anyone motivated - but that still hides it much better against anything automated).
Also, just expose a new "DISABLE_SEGMENT" env var to opt out of sending segment events. Remains backwards compatible with overwriting the default segment write key with an empty string.
> compile segment write key into the binary & rotate key

- infra/sentry.go
This same is not an issue on the frontend, because we don't have the sentry middleware
> do not send request body to sentry

- mocks/enforce_security.go
- repositories/case_repository.go
- repositories/migrations/20250512144400_change_case_index.sql
- usecases/case_usecase.go
- usecases/security/enforce_security.go
- usecases/security/enforce_security_user_test.go
* Change default case ordering as specified by MAR-959.
* Centralize case action side effects (unboosting and self-assigning).
> Various case manager improvements

- usecases/ast_expression_usecase.go
- usecases/ast_expression_usecase_test.go
Two bugs became visible with Swan's data model:
- some database accessors that should be available in the builder, would be returned only randomly (e.g. sometimes you'd get `transactions.accounts.account_holder.aml_score`, sometimes you'd get `transactions.card.accounts.account_holder.aml_score` instead, etc)
- sometimes, the backend would return database accessors that are plainly not valid - like `transactions.card.accounts.account_holder.project.aml_score`. This was due to some pointer confusion.
The diff is more test cases than actual code change.
As you may guess by reading it, it took more time to find the issue than to fix it (perfect storm of recursion and slice pointer spaghetti....).
Previously, the database accessors that were returned allowed loops (accessors going through the …
> fix error on returned database accessors

- .env.example
- cmd/server.go
- models/decision.go
- models/sanction_check.go
- pure_utils/map.go
- usecases/custom_list_usecase.go
- usecases/decision_usecase.go
- usecases/evaluate_scenario/evaluate_sanction_check.go
- usecases/evaluate_scenario/evaluate_scenario.go
- usecases/ingestion_usecase.go
- usecases/scheduled_execution/async_decision_job.go
- usecases/webhook_events_usecase.go
- utils/context_logging.go
- utils/logging.go
- Decision storage in now measured and logged
- Each decision, on top of logging the overall evaluation duration now also logs:
- Each macro-step in the decision process (trigger expression, rules execution, sanctions check, name recognition)
- Each rule individual duration
- Add a `LOG_LEVEL` knob (set to `info` or `debug`) to control how verbose JSON and GCP adapters are
> Improved logging for decisions.

- repositories/case_repository.go
- Remove ordering based on assignment status
- Boosted cases are now prioritized depending on the pagination order
> feat(cases): rework case ordering

- .github/workflows/backend_test_workflow.yaml
- .vscode/settings.json
- api/handle_cases.go
- api/handle_client_data.go
- dto/client_data_object.go
- dto/entity_annotation.go
- dto/entity_annotation_test.go
- models/client_data_object.go
- models/entity_annotation.go
- models/entity_annotation_payload.go
- pubapi/tests/e2e_test.go
- repositories/entity_annotation_repository.go
- usecases/entity_annotations_usecase.go
- usecases/ingested_data_reader_usecase.go
See openapi spec change in https://github.com/checkmarble/marble-frontend/pull/799
I went ahead and implemented grouped by tag type in the backend, because I figured _someone_ would have to do it systematically when displaying them, so we might as well do it in the backend where it minimizes data manipulation. But you let me know if this is overengineered @ChibiBlasphem .
Nb: the `annotations` nested object is not required, and will be only present if any annotations are present.
New example of output payload:
```json
...
{
"pivot_object_id": "account_id",
"pivot_value": "account_id",
"pivot_id": "038f72a2-2c98-47e6-ba85-28547075aafc",
"pivot_type": "object",
"pivot_object_name": "accounts",
"pivot_field_name": "object_id",
"is_ingested": true,
"pivot_object_data": {
"metadata": { …
```
> return ingested object tags along with pivot objects in a case

- repositories/case_repository.go
- usecases/case_usecase.go
- usecases/suspicious_activity_report_usecase.go
This touches on the side effects performed on a case when an action is taken, namely:
- The case going to "Investingating" if it is pending is now a side effect.
- Trigger side effect on rule snooze and suspicious activity report actions.
- Fix side effects on case snoozing and unsnoozing (since one of the side effect is to unboost, we lost the snooze effect).
- Generalize side effects when assigning a case.
Also, remove the 409 if trying to unsnooze a case that is not snoozed.
> Reorder and add more case action side effects.

- mocks/custom_list_repository.go
- repositories/custom_list_repository.go
- usecases/ast_eval/evaluate/evaluate_custom_list_values.go
- usecases/ast_eval/evaluate/evaluate_custom_list_values_test.go
- usecases/custom_list_usecase.go
This PR makes it so deleted lists can still be used during scenario evaluation, but do not appear elsewhere.
> Allow reading from soft-deleted custom lists during scenario evaluation.

- repositories/migrations/20250424120000_add_fuzzystrmatch_extension.sql
Moving the extension to be housed in a specific schema requires that the current user be the owner of the extension. This causes issue on platform where the managed database precreates the extension with their administrative roles.
This checks whether the current user is the owner, and only moves the extension if so.
> Replace migration moving pg_trgm to check if we are extension owner.

- api/handle_client_data.go
- api/handle_entity_annotations.go
- api/routes.go
- dto/entity_annotation.go
- models/case_event.go
- models/entity_annotation.go
- repositories/entity_annotation_repository.go
- usecases/case_usecase.go
- usecases/entity_annotations_usecase.go
- usecases/usecases_with_creds.go
This PR creates a link between an entity annotation and the case it was added from (if applicable):
* Any annotation created will also create a case event of type `entity_annotated`.
* A file annotation will attach the file to the case.
It also fixes an issue with the client object viewer where the models would not be serialized.
> Case events for annotations

- dto/sanction_check_config_dto.go
- dto/sanction_check_dataset_dto.go
- models/opensanctions.go
- repositories/httpmodels/http_opensanctions_dataset.go
- repositories/httpmodels/http_opensanctions_dataset_freshness.go
- repositories/opensanctions_repository.go
- repositories/opensanctions_repository_test.go
~This adds a new section when configuring screening for a scenario including all lists pertaining to politically exposed people.~
This PR:
- Removes the restriction on _which_ datasets we consider for showing in the app (before, we only displayed `sanctions` datasets
- We add a new field to the dataset spec we return, `tag`, which represents what kind of category the dataset is. The list of possible tags for now is:
- `adverse-media`
- `third-parties`
- `peps`
- `sanctions`
To note, quite a few dataset are not classified into one of those superset datasets, and therefore will not have a tag.
The OpenSanctions / Yente endpoint we use also changes to target `/match/default`, instead of `/match/sanctions`.
Finally, to prepare for !1023 (that will separate label name recognition config and …
> Add all datasets, tagged, to the list of datasets

- repositories/migrations/20250117095221_fuzzy_match_on_case_name.sql
- repositories/migrations/20250424120000_add_fuzzystrmatch_extension.sql
This PR tries to be conservative with the way we set up Postgres extensions. Because some managed services already have those extensions created in a way we cannot move them.
> Safe create extensions and remove drop extensions.

- dto/sanction_check_dto.go
- models/sanction_check.go
- repositories/httpmodels/http_opensanctions_result.go
- usecases/sanction_check_usecase.go
We used to only check for whitelisted match against the main entity ID at the time of the screening. This completely shadowed that an entity can have its ID changed over its lifetime.
This PR now considers all previous "referents" IDs when checking whether the match was whitelisted or not.
> Consider all entity referents when checking against whitelists.

- dto/client_data_object.go
- dto/entity_annotation.go
- models/client_data_object.go
- usecases/ingested_data_reader_usecase.go
Incremental changes to the API consumed by the case manager, to facilitate some data display by the frontend following QA of object annotations.
> return information on "can be annotaged" status of a client object

- pure_utils/nullables.go
- pure_utils/nullables_test.go
This PR shamelessly pulls and edits `nullable.go` from #1028 to differentiate nullable values from JSON decoding, to determine whether a field was:
* omitted entirely
* provided but null
* provided and set
This will overall be useful for `PATCH` endpoints to know whether a value was changed or "reset".
> Differentiate between set/null/valid values from JSON.

- api/handle_client_data.go
- dto/client_data_object.go
- models/client_data_object.go
- repositories/ingested_data_read_repository.go
- usecases/ai_agent_usecase.go
- usecases/ingested_data_reader_usecase.go
This adds global metadata with ingested data field statistics to the navigation endpoint. Notably, it gives for each field:
* The field type as defined in the data model
* If it is a string, if it is a recognized format (for now, `uuid`)
* The maximum length of the values (order of magnitude for numbers, length for strings)
These should be considered as hints for the frontend to adapt the display.
> Return field statistics on navigation.

- repositories/migrations/20250605000000_allow_multiple_screenings.sql
We do not have foreign keys on some tables, purposefully, to improve performance. This is the case for sanction_checks->decisions, which meant that sanction checks would live on after an organization was deleted. This is problematic now because we need all sanction checks to have an existing decision.
> Delete orphan sanction checks

- pubapi/tests/fixtures/sanction_checks.yml
- pubapi/tests/setup_test.go
- pubapi/tests/specs/v1/screening.go
The public API was missing some tests when interacting with OpenSanctions, this adds functional testing for both search and refine.
> Add public API tests for search and refine.

- usecases/evaluate_scenario/evaluate_screening.go
This PR fixes the no hit screening results having a wrong error.
> Do not set error code on no hit screenings.

- .env.example
- api/configuration.go
- api/dependencies.go
- api/handle_config.go
- api/handle_post_firebase_id_token.go
- api/routes.go
- cmd/batch_ingestion.go
- cmd/scheduled_executor.go
- cmd/send_pending_webhook_events.go
- cmd/server.go
- cmd/worker.go
- dto/config_dto.go
- infra/config.go
- infra/firebase_client.go
- integration_test/init_test.go
- pubapi/tests/setup_test.go
- repositories/blob_repository.go
- repositories/repositories.go
This endpoint will rule them all, it merges:
- /version
- /is-sso-available
- /signup-status
And adds more data for the backend to be able to send the frontend its configurationon the fly.
---
The goal, ultimately, is to offload the frontend from configuration, as much as possible for directives not strictly related to the frontend (or secret ones). We will take advantage that there is constant communication between the two to provide essential parameters through the new `/config` endpoint.
There are several advantages:
- It becomes impossible to have configuration drift between the backend and frontend
- Configuration is more centralized and partly less duplicated
- Relaunching the backend is usually sufficient to perform configuration changes
This PR also tries to determine a few sane …
> Created a /config endpoint.

- .gitignore
- api/handle_cases.go
- api/routes.go
- dto/agent_dto/agent_printer.go
- dto/agent_dto/case.go
- dto/agent_dto/data_model.go
- dto/agent_dto/decisions.go
- dto/case_review.go
- go.mod
- go.sum
- mocks/scenario_iteration_read_repository.go
- models/ai_agent_config.go
- models/case_review.go
- models/data_model.go
- models/screening.go
- pure_utils/maps.go
- repositories/ingested_data_read_repository.go
- usecases/ai_agent_usecase.go
- usecases/data_model_usecase.go
- usecases/ingested_data_reader_usecase.go
- usecases/usecases_with_creds.go
The agent takes some input data, namely the following (all in json format unless specified otherwise):
- data model of the org
- case base metadata
- case events
- Marble-input description of the organization's activity
- definition of all the rules that are used in decisions present in the case
- decision result with rule execution details for every decision in the case
- for every "pivot object" present in the case (should be just one in most cases):
- previous cases for the entity (without rule exec details)
- data from the tables where we can navigate to from the pivot object entity, as in the case manager, formatted in csv format:
- all the related rows/columns for entities that have fewer than 100 rows
- 500 most recent entries for the 15 most relevant/useful columns (as determined …
> Case review AI agent pipeline

- go.mod
- go.sum
- models/ai_agent_config.go
- usecases/ai_agent_usecase.go
Option #1 I have to bypass the vertex AI rate limiting issue.
I'll try to merge in staging later today to do some test runs.
I'm trying to use it with [this](https://openrouter.ai/settings/presets/new) LLM router - which isn't prod compatible for us because of no control on where data is treated geographically, but good enough for some tests in staging.
Fully compatible with openAI SDK.
The alternative is to try Gemini models in "API key" mode (rather than in vertex AI mode), which _may_ on paper have different rate limiting properties than vertex AI (though it's all very unclear how it behaves _effectively_ and only usage will tell).
> test - migrate to openai SDK for ai agent

- README.md
Updated the README.md to:
•	Include the GOOSE_MIGRATION_DIR environment variable in the example setup, which is required to run goose from the repository root.
•	Reflect the correct working directory for running goose down (previously repositories/migrations, now the root folder).
> docs: clarify goose instructions

- dto/organization_dto.go
- models/organization.go
- repositories/dbmodels/db_organization.go
- repositories/migrations/20250709131753_add_organization_public_id.sql
This pull request introduces a new `PublicId` field to the `Organization` model, designed to provide a UUID for external tools, making links easier and avoiding exposure of internal IDs. Changes span across multiple files to integrate this field into the API, database models, and migrations.
* [`repositories/migrations/20250709131753_add_organization_public_id.sql`](diffhunk://#diff-0d2ead86b45e41338016595495740a637d09655268573eb3a262066a28454537R1-R14): Added a new `public_id` column to the `organizations` table with a unique UUID default value generated by `uuid_generate_v4()`. This ensures every organization has a distinct external identifier.
* [`repositories/dbmodels/db_organization.go`](diffhunk://#diff-00fd0e6f9c59a34bef8bec124cfd98c8bc77e4b89b5c79cf1e9358c5e92c3095R6-R11): Updated …
> feat(organization): public_id field to organization model

- .github/workflows/backend_deploy_workflow.yaml
- .github/workflows/deploy_production.yaml
It was all nice and cool for faster deployments in prod, but we missed out on the prod app version being available in the backend container which was annoying.
> remove the logic that bypasses build for prod deployment

- api/routes.go
- pubapi/v1/routes.go
This adds all the `/v1beta` routes under a new prefix: `/v1`.
The same routes are still mounted under `/v1beta` for both backward compatibility (for users using it) and to ease testing of new additions to V1.
`/v1beta` now also sources routes from a second route function so we can safely add new endpoints to that API version until they stabilize.
> Publish API v1 and maintain v1beta backward compatibility.

- api/dependencies.go
- cmd/server.go
- integration_test/init_test.go
- mocks/firebase_token_verifier.go
- pubapi/tests/setup_test.go
- repositories/firebase/admin.go
- usecases/usecases.go
- usecases/usecases_with_creds.go
- usecases/user_usecase.go
This PR adds two side effects to creating a Marble user:
* The matching Firebase user is created is it does not already exist
* The password reset email is sent (if the user was indeed created)
This might be a breaking (actually breaking) change if a user managed their IAM manually when setting up Firebase. If they used a permission-less service account (which is sufficient for login), creating users would fail on this branch because we would not have the permission to create the user.
Either we relax error handling on that path (ignoring not being able to create the user - not recommended since it would bring hard to debug errors), or we communicate that the service account requires the **Firebase Authentication Admin** permission.
This **does not**:
* Delete Firebase users when Marble …
> Create the Firebase user at the same time as the Marble user.

- repositories/auto_assignment_repository.go
The code was emitting an error when `FindNextAutoAssignableUserForInbox` returned no rows, this PR handles this case.
> Handle no rows returned for next assignable user.

- repositories/migrations/20250820142413_alter_temp_file_ref_non_null.sql
fix: https://marble-eu.sentry.io/issues/59004707/?alert_rule_id=193450&alert_type=issue&notification_uuid=94bec797-d449-4b8b-a91e-136ea703cf8e&project=4509310347640912&referrer=slack 
`file_temp_reference` column was set as nullable column but the data model in code expect a non null value. 
I changed the nullable setting of this column and fill a default value for existing row. 
We don't have many rows so the migration should be ok and fast
> feat(migrations): add migration to set file_temp_reference as NOT NULL

- docker-compose.yml
This pull request adds a new service to the `docker-compose.yml` file. The main change is the introduction of a `worker-monitor` service for monitoring purposes.
New service added:
* Added a `worker-monitor` service using the `ghcr.io/riverqueue/riverui:latest` image, exposing port 8001 and configuring the database connection via the `DATABASE_URL` environment variable.
Notes:
I chose port 8001 arbitrarily, but it can be changed if needed.
> feat(worker): add worker monitor service based on river UI

- usecases/ai_agent/ai_agent_usecase.go
This pull request makes a targeted improvement to the `CreateCaseReviewSync` method in `ai_agent_usecase.go`. The main change ensures that the code correctly checks whether `objectTables` contains any data before proceeding, rather than just checking if it is non-nil. This prevents potential issues when `objectTables` is an empty slice.
- Logic improvement:
* Updated the conditional check from `objectTables != nil` to `len(objectTables) > 0` to ensure that further processing only occurs when there is actually data present in `objectTables`.
I also wrapped the second step of the case review to avoid executing it when `tablesWithLargRowNbs` is empty. The prompt construction depends on this map, as well as column filtering, etc. This is mainly a fix to prevent issues in production. I think …
> fix(ai_case_review): update objectTables check to ensure non-empty slice before processing

- repositories/opensanctions_repository.go
We were not passing any `content-type` to Yente's match request, which was okay for Yente, but not for servers more respectful of HTTP semantics. 👀
> Be explicit about OpenSanctions match request content-type.

- .env.example
- cmd/server.go
- cmd/worker.go
- go.mod
- go.sum
- infra/config.go
- infra/tracing.go
- repositories/opensanctions_repository.go
This PR implements a probabilistic sampler for our tracing setup, it applies a default rate of `0.3` based on the Trace ID that is overriden by:
* Statically defined rules based on HTTP route prefix.
* Static analysis of the SQL queries (to remove `set_config` and duplicate `prepare` statements)
The goal here is to not be overwhelmed by traces from heavily called endpoints (decisions, ingestion, etc.) and to completely disable traces for infrastructure endpoints (such as /liveness).
> Add custom OTEL sampler based on route prefix.

- cmd/worker.go
- jobs/middlewares.go
- repositories/decisions_repository.go
- repositories/sql_to_row.go
- usecases/scheduled_execution/auto_assignment_job.go
- usecases/scheduled_execution/index_cleanup_job.go
- usecases/scheduled_execution/index_creation_job.go
- usecases/scheduled_execution/index_rollover_job.go
- usecases/scheduled_execution/match_enrichment_job.go
- usecases/scheduled_execution/offloading_job.go
- Implement Timeout() on all river jobs, so that they are not aggressively rescued by the river rescuer routine (which could have weird effects if the job is still running)
- disable hash joins in the query that lists decisions to offload - and run in a transaction in order to do so (at the cost of some more loop state handling)
- add spans in offloading routine
> offloading improvement

- usecases/scheduled_execution/offloading_job.go
We had a memory leak caused by using `defer` in a (lengthy) hot loop. The deferred function would hold a reference to the writer-to-be-closed and prevent the garbage collector from freeing the memory, leading to OOM.
> Fixed memory leak caused by defer retaining writers.

- dto/openapi.go
Updated the error response schema reference from `ErrorDto` to `Error` to ensure consistency with the OpenAPI schema definitions.
`ErrorDto` is not defined in V1 OpenAPI specs and the `ingestion` endpoint return an Error and not an ErrorDto
> fix(openapi v1): fix return type from ErrorDto to Error

- cmd/server.go
- infra/tracing.go
- repositories/opensanctions_repository.go
This registers the propagators so they can be used by `otelhttp` to send span context to upstream services.
> Register propagator into OTEL machinery and use them for OpenSanctions.

- repositories/migrations/20250903212000_created_at_on_dec_rules.sql
It's a pain not to have this denormalized.
Won't be usable before we do a full rewrite of decision_rules (ouch).
But we might as well start writing them for new rows.
> add migration for created_at on decision_rules

- dto/organization_dto.go
- repositories/migrations/20250905153700_allowed_network_trail.sql
This adds two items to our allowed network feature:
* Modification of the allowed networks will be logged into the audit trail.
* Plain IP address (without a CIDR mask) are now allowed. They still need to be valid addresses for their family and will be suffixed with `/32` or `/128` depending on it.
> Support plain IP addresses for allowed network and audit trail

- api/handle_license.go
- cmd/batch_ingestion.go
- cmd/common.go
- cmd/scheduled_executor.go
- cmd/send_pending_webhook_events.go
- cmd/server.go
- cmd/worker.go
- infra/verify_license.go
- usecases/license_usecase.go
- usecases/metrics_collection/constant.go
- usecases/usecases.go
This pull request improves license validation by having the server and worker fetch the deployment ID and send it to the Marble SaaS for license checking. If the license is valid, Marble SaaS records a new metric. License verification now occurs at server and worker startup, immediately after repository initialization.
> feat(license): send deployment id with the license key

- .vscode/launch.json
- cmd/worker.go
- integration_test/init_test.go
- integration_test/scenario_flow_test.go
- mocks/task_queue_repository.go
- models/river_job.go
- repositories/dbmodels/db_decision_rule.go
- repositories/decisions_repository.go
- repositories/task_queue_repository.go
- usecases/decision_usecase.go
- usecases/decision_workflows/worker.go
- usecases/usecases_with_creds.go
- Introduced a new worker for processing decision workflows
- Updated task queue repository to support enqueuing decision workflow tasks.
- Implemented logic for handling decision workflows in the usecases layer by replacing the process by enqueue function
- The behavior for creating decisions asynchronously in batch mode remains unchanged.
> feat: add DecisionWorkflowsWorker

- cmd/common.go
- cmd/server.go
- models/case.go
- repositories/case_repository.go
- repositories/marble_db_repository.go
Using 
```sql
with words as (
select 'case' as w
)
select name, w as match,
similarity(name, w) as sim_bad, word_similarity(name,w) as sim2_bad, strict_word_similarity(name, w) as sim3_bad,
similarity(w,name) as sim4_bad, word_similarity(w,name) as sim5_good, strict_word_similarity(w,name) as sim6_good
--, 1-levenshtein(name, w)::float8/GREATEST(LENGTH(name), LENGTH(w)) as lev1
from cases
inner join words on(true)
where org_id='e617f1de-a1ba-4a08-8202-e2a810367a31'
and assigned_to='d14e8e4e-b844-409b-8422-2ab9a1772091'
order by 4 desc;
```
we get this 
or this 
Long story short, `word_similarity` is better aligned with our usecase, and the shorter string should be the first argument (when there is an obvious candidate for shorter string, which is the case here - otherwise we may need to …
> proposed improvement for string similarity matching on cases list

- .github/workflows/backend_deploy_workflow.yaml
- .github/workflows/backend_test_workflow.yaml
- .github/workflows/build_and_test.yaml
- move golangci-lint to a separate job to run in parallel with tests, for faster execution
- also bump the version of all CI actions, quite a few have a new version
> upgrade actions and separate job for lint

- pubapi/openapi/v1.yml
This pull request updates the OpenAPI schema to include missing fields: **nationality** for Person and **country** for Company. These fields are already supported by the endpoint.
> fix: add missing field in public openapi

- api/routes.go
- usecases/token/validator.go
- usecases/token/validator_test.go
- utils/auth.go
- utils/auth_test.go
Simple renaming of things, for all the times I had to search "Validate()" in the codebase and didn't find the ones I wanted
> rename some auth things

- usecases/decision_workflows/worker.go
Large volumes of decision workflows were taking more than seconds because it was getting repeatedly the data model with enum values, creating loads of unnecessary requests.
I could (and will) fix this for now on the managed worker, but I want to include this in the hotfix branch before we release OS.
> fix decision workflow execution data model get

- cmd/worker.go
- infra/tracing.go
- repositories/blob_repository.go
- don't create spans for bucket blob opening (unless requested by debug env var)
- lower default sampling for decision workflows (now dominant in traces)
- don't sample "pool.acquire" (one third of our traces, done every time we do a query outside of a transaction
- rename app name for worker so we can filter traces by api or worker
> small tracing improvements

- cmd/server.go
A license check is now performed on backend startup to abort early if authentication is configured through OIDC without having the SSO entitlement.
> Abort if OIDC is set up without SSO license entitlement

- repositories/decisions_repository.go
Because postgres is dump, and will apply the correct plan on a "count" query, will apply the correct plan on the query with an org/watermark where the query will return "limit" rows, but will arbitrarily seq scan the decisions table if I want fields from one row of decisions and rules 🤷
> fix: prevent seqscan for offloading query

- dto/analytics.go
- repositories/migrations/20251003090300_create_analytics_export_index.sql
- usecases/analytics_query_usecase.go
- usecases/scheduled_execution/analytics_export_job.go
- usecases/usecases_with_creds.go
* Guard decision rules and screenings behind a license entitlement
* Guard most graph generation behind a license entitlement
* Create specialized index to efficiently export decisions (`(org_id, trigger_object_type, created_at, id)`)
* Take client timezone into account for time bucketing
* _[work in progress]_
> Various analytics improvements
